/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Actualizaciones;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActualizacionesRecord extends UpdatableRecordImpl<ActualizacionesRecord> implements Record12<Integer, String, String, String, String, Integer, String, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1656932278;

    /**
     * Setter for <code>oko.Actualizaciones.idActualizacion</code>.
     */
    public void setIdactualizacion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.idActualizacion</code>.
     */
    public Integer getIdactualizacion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.Actualizaciones.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.Actualizaciones.pathUpdate</code>.
     */
    public void setPathupdate(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.pathUpdate</code>.
     */
    public String getPathupdate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.Actualizaciones.changeLog</code>.
     */
    public void setChangelog(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.changeLog</code>.
     */
    public String getChangelog() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oko.Actualizaciones.md5hash</code>.
     */
    public void setMd5hash(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.md5hash</code>.
     */
    public String getMd5hash() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oko.Actualizaciones.versionCode</code>.
     */
    public void setVersioncode(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.versionCode</code>.
     */
    public Integer getVersioncode() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>oko.Actualizaciones.versionName</code>.
     */
    public void setVersionname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.versionName</code>.
     */
    public String getVersionname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oko.Actualizaciones.versionNameUpdater</code>.
     */
    public void setVersionnameupdater(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.versionNameUpdater</code>.
     */
    public String getVersionnameupdater() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oko.Actualizaciones.permitirActualizar</code>.
     */
    public void setPermitiractualizar(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.permitirActualizar</code>.
     */
    public Integer getPermitiractualizar() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>oko.Actualizaciones.tipo</code>.
     */
    public void setTipo(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.tipo</code>.
     */
    public Integer getTipo() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>oko.Actualizaciones.fechaPublicado</code>.
     */
    public void setFechapublicado(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.fechaPublicado</code>.
     */
    public Timestamp getFechapublicado() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>oko.Actualizaciones.fechaInsert</code>.
     */
    public void setFechainsert(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>oko.Actualizaciones.fechaInsert</code>.
     */
    public Timestamp getFechainsert() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, Integer, String, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, Integer, String, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Actualizaciones.ACTUALIZACIONES.IDACTUALIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Actualizaciones.ACTUALIZACIONES.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Actualizaciones.ACTUALIZACIONES.PATHUPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Actualizaciones.ACTUALIZACIONES.CHANGELOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Actualizaciones.ACTUALIZACIONES.MD5HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Actualizaciones.ACTUALIZACIONES.VERSIONCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Actualizaciones.ACTUALIZACIONES.VERSIONNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Actualizaciones.ACTUALIZACIONES.VERSIONNAMEUPDATER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Actualizaciones.ACTUALIZACIONES.PERMITIRACTUALIZAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Actualizaciones.ACTUALIZACIONES.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Actualizaciones.ACTUALIZACIONES.FECHAPUBLICADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Actualizaciones.ACTUALIZACIONES.FECHAINSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdactualizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPathupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getChangelog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMd5hash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVersioncode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getVersionname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getVersionnameupdater();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPermitiractualizar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getFechapublicado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getFechainsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value1(Integer value) {
        setIdactualizacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value3(String value) {
        setPathupdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value4(String value) {
        setChangelog(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value5(String value) {
        setMd5hash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value6(Integer value) {
        setVersioncode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value7(String value) {
        setVersionname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value8(String value) {
        setVersionnameupdater(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value9(Integer value) {
        setPermitiractualizar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value10(Integer value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value11(Timestamp value) {
        setFechapublicado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord value12(Timestamp value) {
        setFechainsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActualizacionesRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, String value7, String value8, Integer value9, Integer value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActualizacionesRecord
     */
    public ActualizacionesRecord() {
        super(Actualizaciones.ACTUALIZACIONES);
    }

    /**
     * Create a detached, initialised ActualizacionesRecord
     */
    public ActualizacionesRecord(Integer idactualizacion, String nombre, String pathupdate, String changelog, String md5hash, Integer versioncode, String versionname, String versionnameupdater, Integer permitiractualizar, Integer tipo, Timestamp fechapublicado, Timestamp fechainsert) {
        super(Actualizaciones.ACTUALIZACIONES);

        set(0, idactualizacion);
        set(1, nombre);
        set(2, pathupdate);
        set(3, changelog);
        set(4, md5hash);
        set(5, versioncode);
        set(6, versionname);
        set(7, versionnameupdater);
        set(8, permitiractualizar);
        set(9, tipo);
        set(10, fechapublicado);
        set(11, fechainsert);
    }
}
