/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Canales;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CanalesRecord extends UpdatableRecordImpl<CanalesRecord> implements Record10<Integer, String, String, String, String, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = -42521675;

    /**
     * Setter for <code>oko.Canales.idcanal</code>.
     */
    public void setIdcanal(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.Canales.idcanal</code>.
     */
    public Integer getIdcanal() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.Canales.nombre_ES</code>.
     */
    public void setNombreEs(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.Canales.nombre_ES</code>.
     */
    public String getNombreEs() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.Canales.nombre_DE</code>.
     */
    public void setNombreDe(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.Canales.nombre_DE</code>.
     */
    public String getNombreDe() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.Canales.nombre_EN</code>.
     */
    public void setNombreEn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.Canales.nombre_EN</code>.
     */
    public String getNombreEn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oko.Canales.nombre_FR</code>.
     */
    public void setNombreFr(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.Canales.nombre_FR</code>.
     */
    public String getNombreFr() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oko.Canales.nombre_IT</code>.
     */
    public void setNombreIt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.Canales.nombre_IT</code>.
     */
    public String getNombreIt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oko.Canales.thumbnail</code>.
     */
    public void setThumbnail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oko.Canales.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oko.Canales.available</code>.
     */
    public void setAvailable(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>oko.Canales.available</code>.
     */
    public Integer getAvailable() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>oko.Canales.idLocalizacion</code>.
     */
    public void setIdlocalizacion(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>oko.Canales.idLocalizacion</code>.
     */
    public Integer getIdlocalizacion() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>oko.Canales.idEmpresa</code>.
     */
    public void setIdempresa(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>oko.Canales.idEmpresa</code>.
     */
    public Integer getIdempresa() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Canales.CANALES.IDCANAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Canales.CANALES.NOMBRE_ES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Canales.CANALES.NOMBRE_DE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Canales.CANALES.NOMBRE_EN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Canales.CANALES.NOMBRE_FR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Canales.CANALES.NOMBRE_IT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Canales.CANALES.THUMBNAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Canales.CANALES.AVAILABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Canales.CANALES.IDLOCALIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Canales.CANALES.IDEMPRESA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcanal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombreEs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNombreDe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNombreEn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNombreFr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNombreIt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIdlocalizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getIdempresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value1(Integer value) {
        setIdcanal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value2(String value) {
        setNombreEs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value3(String value) {
        setNombreDe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value4(String value) {
        setNombreEn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value5(String value) {
        setNombreFr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value6(String value) {
        setNombreIt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value7(String value) {
        setThumbnail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value8(Integer value) {
        setAvailable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value9(Integer value) {
        setIdlocalizacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord value10(Integer value) {
        setIdempresa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanalesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CanalesRecord
     */
    public CanalesRecord() {
        super(Canales.CANALES);
    }

    /**
     * Create a detached, initialised CanalesRecord
     */
    public CanalesRecord(Integer idcanal, String nombreEs, String nombreDe, String nombreEn, String nombreFr, String nombreIt, String thumbnail, Integer available, Integer idlocalizacion, Integer idempresa) {
        super(Canales.CANALES);

        set(0, idcanal);
        set(1, nombreEs);
        set(2, nombreDe);
        set(3, nombreEn);
        set(4, nombreFr);
        set(5, nombreIt);
        set(6, thumbnail);
        set(7, available);
        set(8, idlocalizacion);
        set(9, idempresa);
    }
}
