/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Contenidocanal;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContenidocanalRecord extends UpdatableRecordImpl<ContenidocanalRecord> implements Record7<Integer, String, String, Integer, String, Timestamp, Integer> {

    private static final long serialVersionUID = -1981502884;

    /**
     * Setter for <code>oko.ContenidoCanal.idcontenidoCanal</code>.
     */
    public void setIdcontenidocanal(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.ContenidoCanal.idcontenidoCanal</code>.
     */
    public Integer getIdcontenidocanal() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.ContenidoCanal.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.ContenidoCanal.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.ContenidoCanal.thumbnail</code>.
     */
    public void setThumbnail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.ContenidoCanal.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.ContenidoCanal.tipo</code>.
     */
    public void setTipo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.ContenidoCanal.tipo</code>.
     */
    public Integer getTipo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>oko.ContenidoCanal.textoImagen</code>.
     */
    public void setTextoimagen(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.ContenidoCanal.textoImagen</code>.
     */
    public String getTextoimagen() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oko.ContenidoCanal.fechaInsert</code>.
     */
    public void setFechainsert(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.ContenidoCanal.fechaInsert</code>.
     */
    public Timestamp getFechainsert() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>oko.ContenidoCanal.idcanal</code>.
     */
    public void setIdcanal(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>oko.ContenidoCanal.idcanal</code>.
     */
    public Integer getIdcanal() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, Timestamp, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, Timestamp, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Contenidocanal.CONTENIDOCANAL.IDCONTENIDOCANAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Contenidocanal.CONTENIDOCANAL.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Contenidocanal.CONTENIDOCANAL.THUMBNAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Contenidocanal.CONTENIDOCANAL.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Contenidocanal.CONTENIDOCANAL.TEXTOIMAGEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Contenidocanal.CONTENIDOCANAL.FECHAINSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Contenidocanal.CONTENIDOCANAL.IDCANAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcontenidocanal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTextoimagen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getFechainsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdcanal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidocanalRecord value1(Integer value) {
        setIdcontenidocanal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidocanalRecord value2(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidocanalRecord value3(String value) {
        setThumbnail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidocanalRecord value4(Integer value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidocanalRecord value5(String value) {
        setTextoimagen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidocanalRecord value6(Timestamp value) {
        setFechainsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidocanalRecord value7(Integer value) {
        setIdcanal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidocanalRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Timestamp value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContenidocanalRecord
     */
    public ContenidocanalRecord() {
        super(Contenidocanal.CONTENIDOCANAL);
    }

    /**
     * Create a detached, initialised ContenidocanalRecord
     */
    public ContenidocanalRecord(Integer idcontenidocanal, String url, String thumbnail, Integer tipo, String textoimagen, Timestamp fechainsert, Integer idcanal) {
        super(Contenidocanal.CONTENIDOCANAL);

        set(0, idcontenidocanal);
        set(1, url);
        set(2, thumbnail);
        set(3, tipo);
        set(4, textoimagen);
        set(5, fechainsert);
        set(6, idcanal);
    }
}
