/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Contenidosmultimedia;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContenidosmultimediaRecord extends UpdatableRecordImpl<ContenidosmultimediaRecord> implements Record9<Integer, Integer, String, String, String, Timestamp, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1605500992;

    /**
     * Setter for <code>oko.ContenidosMultimedia.idContenidoMultimedia</code>.
     */
    public void setIdcontenidomultimedia(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.idContenidoMultimedia</code>.
     */
    public Integer getIdcontenidomultimedia() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.ContenidosMultimedia.tipo</code>.
     */
    public void setTipo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.tipo</code>.
     */
    public Integer getTipo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>oko.ContenidosMultimedia.texto</code>.
     */
    public void setTexto(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.texto</code>.
     */
    public String getTexto() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.ContenidosMultimedia.url</code>.
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.url</code>.
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oko.ContenidosMultimedia.urlThumbnail</code>.
     */
    public void setUrlthumbnail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.urlThumbnail</code>.
     */
    public String getUrlthumbnail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oko.ContenidosMultimedia.fechaInsert</code>.
     */
    public void setFechainsert(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.fechaInsert</code>.
     */
    public Timestamp getFechainsert() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>oko.ContenidosMultimedia.idUsuarioEmisor</code>.
     */
    public void setIdusuarioemisor(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.idUsuarioEmisor</code>.
     */
    public Integer getIdusuarioemisor() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>oko.ContenidosMultimedia.idDispositivoVirtual</code>.
     */
    public void setIddispositivovirtual(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.idDispositivoVirtual</code>.
     */
    public Integer getIddispositivovirtual() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>oko.ContenidosMultimedia.idContenidoFisico</code>.
     */
    public void setIdcontenidofisico(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>oko.ContenidosMultimedia.idContenidoFisico</code>.
     */
    public Integer getIdcontenidofisico() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, String, Timestamp, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, String, Timestamp, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDCONTENIDOMULTIMEDIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.TEXTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.URLTHUMBNAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.FECHAINSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDUSUARIOEMISOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDDISPOSITIVOVIRTUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDCONTENIDOFISICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcontenidomultimedia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTexto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrlthumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getFechainsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdusuarioemisor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIddispositivovirtual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIdcontenidofisico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value1(Integer value) {
        setIdcontenidomultimedia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value2(Integer value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value3(String value) {
        setTexto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value4(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value5(String value) {
        setUrlthumbnail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value6(Timestamp value) {
        setFechainsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value7(Integer value) {
        setIdusuarioemisor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value8(Integer value) {
        setIddispositivovirtual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord value9(Integer value) {
        setIdcontenidofisico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosmultimediaRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Timestamp value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContenidosmultimediaRecord
     */
    public ContenidosmultimediaRecord() {
        super(Contenidosmultimedia.CONTENIDOSMULTIMEDIA);
    }

    /**
     * Create a detached, initialised ContenidosmultimediaRecord
     */
    public ContenidosmultimediaRecord(Integer idcontenidomultimedia, Integer tipo, String texto, String url, String urlthumbnail, Timestamp fechainsert, Integer idusuarioemisor, Integer iddispositivovirtual, Integer idcontenidofisico) {
        super(Contenidosmultimedia.CONTENIDOSMULTIMEDIA);

        set(0, idcontenidomultimedia);
        set(1, tipo);
        set(2, texto);
        set(3, url);
        set(4, urlthumbnail);
        set(5, fechainsert);
        set(6, idusuarioemisor);
        set(7, iddispositivovirtual);
        set(8, idcontenidofisico);
    }
}
