/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Contenidosfisicos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContenidosfisicosRecord extends UpdatableRecordImpl<ContenidosfisicosRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -1050990325;

    /**
     * Setter for <code>oko.ContenidosFisicos.idContenidoFisico</code>.
     */
    public void setIdcontenidofisico(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.ContenidosFisicos.idContenidoFisico</code>.
     */
    public Integer getIdcontenidofisico() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.ContenidosFisicos.pathContenidoFisico</code>.
     */
    public void setPathcontenidofisico(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.ContenidosFisicos.pathContenidoFisico</code>.
     */
    public String getPathcontenidofisico() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.ContenidosFisicos.pathThumbnail</code>.
     */
    public void setPaththumbnail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.ContenidosFisicos.pathThumbnail</code>.
     */
    public String getPaththumbnail() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Contenidosfisicos.CONTENIDOSFISICOS.IDCONTENIDOFISICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Contenidosfisicos.CONTENIDOSFISICOS.PATHCONTENIDOFISICO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Contenidosfisicos.CONTENIDOSFISICOS.PATHTHUMBNAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdcontenidofisico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPathcontenidofisico();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPaththumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosfisicosRecord value1(Integer value) {
        setIdcontenidofisico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosfisicosRecord value2(String value) {
        setPathcontenidofisico(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosfisicosRecord value3(String value) {
        setPaththumbnail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContenidosfisicosRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContenidosfisicosRecord
     */
    public ContenidosfisicosRecord() {
        super(Contenidosfisicos.CONTENIDOSFISICOS);
    }

    /**
     * Create a detached, initialised ContenidosfisicosRecord
     */
    public ContenidosfisicosRecord(Integer idcontenidofisico, String pathcontenidofisico, String paththumbnail) {
        super(Contenidosfisicos.CONTENIDOSFISICOS);

        set(0, idcontenidofisico);
        set(1, pathcontenidofisico);
        set(2, paththumbnail);
    }
}
