/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Estadocontenidomultimedia;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EstadocontenidomultimediaRecord extends UpdatableRecordImpl<EstadocontenidomultimediaRecord> implements Record6<Integer, Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -510818979;

    /**
     * Setter for <code>oko.EstadoContenidoMultimedia.idEstadoContenidoMultimedia</code>.
     */
    public void setIdestadocontenidomultimedia(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.EstadoContenidoMultimedia.idEstadoContenidoMultimedia</code>.
     */
    public Integer getIdestadocontenidomultimedia() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.EstadoContenidoMultimedia.estado</code>.
     */
    public void setEstado(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.EstadoContenidoMultimedia.estado</code>.
     */
    public Integer getEstado() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>oko.EstadoContenidoMultimedia.feedback</code>.
     */
    public void setFeedback(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.EstadoContenidoMultimedia.feedback</code>.
     */
    public Integer getFeedback() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>oko.EstadoContenidoMultimedia.idMessage</code>.
     */
    public void setIdmessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.EstadoContenidoMultimedia.idMessage</code>.
     */
    public String getIdmessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oko.EstadoContenidoMultimedia.idContenidoMultimedia</code>.
     */
    public void setIdcontenidomultimedia(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.EstadoContenidoMultimedia.idContenidoMultimedia</code>.
     */
    public Integer getIdcontenidomultimedia() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>oko.EstadoContenidoMultimedia.idDispositivoVirtual</code>.
     */
    public void setIddispositivovirtual(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.EstadoContenidoMultimedia.idDispositivoVirtual</code>.
     */
    public Integer getIddispositivovirtual() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDESTADOCONTENIDOMULTIMEDIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.FEEDBACK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDMESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDCONTENIDOMULTIMEDIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDDISPOSITIVOVIRTUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdestadocontenidomultimedia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFeedback();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIdmessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdcontenidomultimedia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIddispositivovirtual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstadocontenidomultimediaRecord value1(Integer value) {
        setIdestadocontenidomultimedia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstadocontenidomultimediaRecord value2(Integer value) {
        setEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstadocontenidomultimediaRecord value3(Integer value) {
        setFeedback(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstadocontenidomultimediaRecord value4(String value) {
        setIdmessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstadocontenidomultimediaRecord value5(Integer value) {
        setIdcontenidomultimedia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstadocontenidomultimediaRecord value6(Integer value) {
        setIddispositivovirtual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstadocontenidomultimediaRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EstadocontenidomultimediaRecord
     */
    public EstadocontenidomultimediaRecord() {
        super(Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA);
    }

    /**
     * Create a detached, initialised EstadocontenidomultimediaRecord
     */
    public EstadocontenidomultimediaRecord(Integer idestadocontenidomultimedia, Integer estado, Integer feedback, String idmessage, Integer idcontenidomultimedia, Integer iddispositivovirtual) {
        super(Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA);

        set(0, idestadocontenidomultimedia);
        set(1, estado);
        set(2, feedback);
        set(3, idmessage);
        set(4, idcontenidomultimedia);
        set(5, iddispositivovirtual);
    }
}
