/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Localizaciones;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocalizacionesRecord extends UpdatableRecordImpl<LocalizacionesRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = -1242231521;

    /**
     * Setter for <code>oko.Localizaciones.idLocalizacion</code>.
     */
    public void setIdlocalizacion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.Localizaciones.idLocalizacion</code>.
     */
    public Integer getIdlocalizacion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.Localizaciones.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.Localizaciones.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.Localizaciones.telefono</code>.
     */
    public void setTelefono(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.Localizaciones.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.Localizaciones.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.Localizaciones.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oko.Localizaciones.idEmpresa</code>.
     */
    public void setIdempresa(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.Localizaciones.idEmpresa</code>.
     */
    public Integer getIdempresa() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Localizaciones.LOCALIZACIONES.IDLOCALIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Localizaciones.LOCALIZACIONES.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Localizaciones.LOCALIZACIONES.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Localizaciones.LOCALIZACIONES.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Localizaciones.LOCALIZACIONES.IDEMPRESA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdlocalizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdempresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalizacionesRecord value1(Integer value) {
        setIdlocalizacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalizacionesRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalizacionesRecord value3(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalizacionesRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalizacionesRecord value5(Integer value) {
        setIdempresa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalizacionesRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocalizacionesRecord
     */
    public LocalizacionesRecord() {
        super(Localizaciones.LOCALIZACIONES);
    }

    /**
     * Create a detached, initialised LocalizacionesRecord
     */
    public LocalizacionesRecord(Integer idlocalizacion, String nombre, String telefono, String email, Integer idempresa) {
        super(Localizaciones.LOCALIZACIONES);

        set(0, idlocalizacion);
        set(1, nombre);
        set(2, telefono);
        set(3, email);
        set(4, idempresa);
    }
}
