/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Notificacionespush;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificacionespushRecord extends UpdatableRecordImpl<NotificacionespushRecord> implements Record10<Integer, String, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -894184660;

    /**
     * Setter for <code>oko.NotificacionesPush.idNotificacionPush</code>.
     */
    public void setIdnotificacionpush(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.idNotificacionPush</code>.
     */
    public Integer getIdnotificacionpush() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.mensaje</code>.
     */
    public void setMensaje(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.mensaje</code>.
     */
    public String getMensaje() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.idMensaje</code>.
     */
    public void setIdmensaje(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.idMensaje</code>.
     */
    public String getIdmensaje() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.tipoDispositivo</code>.
     */
    public void setTipodispositivo(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.tipoDispositivo</code>.
     */
    public Integer getTipodispositivo() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.plataforma</code>.
     */
    public void setPlataforma(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.plataforma</code>.
     */
    public Integer getPlataforma() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.estado</code>.
     */
    public void setEstado(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.estado</code>.
     */
    public Integer getEstado() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.fechaInsercion</code>.
     */
    public void setFechainsercion(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.fechaInsercion</code>.
     */
    public Timestamp getFechainsercion() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.fechaEjecucion</code>.
     */
    public void setFechaejecucion(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.fechaEjecucion</code>.
     */
    public Timestamp getFechaejecucion() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>oko.NotificacionesPush.fechaLanzamiento</code>.
     */
    public void setFechalanzamiento(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>oko.NotificacionesPush.fechaLanzamiento</code>.
     */
    public Timestamp getFechalanzamiento() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Notificacionespush.NOTIFICACIONESPUSH.IDNOTIFICACIONPUSH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Notificacionespush.NOTIFICACIONESPUSH.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Notificacionespush.NOTIFICACIONESPUSH.MENSAJE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Notificacionespush.NOTIFICACIONESPUSH.IDMENSAJE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Notificacionespush.NOTIFICACIONESPUSH.TIPODISPOSITIVO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Notificacionespush.NOTIFICACIONESPUSH.PLATAFORMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Notificacionespush.NOTIFICACIONESPUSH.ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Notificacionespush.NOTIFICACIONESPUSH.FECHAINSERCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Notificacionespush.NOTIFICACIONESPUSH.FECHAEJECUCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Notificacionespush.NOTIFICACIONESPUSH.FECHALANZAMIENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdnotificacionpush();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMensaje();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIdmensaje();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTipodispositivo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPlataforma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getFechainsercion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getFechaejecucion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getFechalanzamiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value1(Integer value) {
        setIdnotificacionpush(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value3(String value) {
        setMensaje(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value4(String value) {
        setIdmensaje(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value5(Integer value) {
        setTipodispositivo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value6(Integer value) {
        setPlataforma(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value7(Integer value) {
        setEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value8(Timestamp value) {
        setFechainsercion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value9(Timestamp value) {
        setFechaejecucion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord value10(Timestamp value) {
        setFechalanzamiento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionespushRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Timestamp value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificacionespushRecord
     */
    public NotificacionespushRecord() {
        super(Notificacionespush.NOTIFICACIONESPUSH);
    }

    /**
     * Create a detached, initialised NotificacionespushRecord
     */
    public NotificacionespushRecord(Integer idnotificacionpush, String token, String mensaje, String idmensaje, Integer tipodispositivo, Integer plataforma, Integer estado, Timestamp fechainsercion, Timestamp fechaejecucion, Timestamp fechalanzamiento) {
        super(Notificacionespush.NOTIFICACIONESPUSH);

        set(0, idnotificacionpush);
        set(1, token);
        set(2, mensaje);
        set(3, idmensaje);
        set(4, tipodispositivo);
        set(5, plataforma);
        set(6, estado);
        set(7, fechainsercion);
        set(8, fechaejecucion);
        set(9, fechalanzamiento);
    }
}
