/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Notificaciones;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificacionesRecord extends UpdatableRecordImpl<NotificacionesRecord> implements Record7<Integer, Integer, Integer, Integer, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = 1212385983;

    /**
     * Setter for <code>oko.Notificaciones.idNotificacion</code>.
     */
    public void setIdnotificacion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.Notificaciones.idNotificacion</code>.
     */
    public Integer getIdnotificacion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.Notificaciones.status</code>.
     */
    public void setStatus(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.Notificaciones.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>oko.Notificaciones.tipo</code>.
     */
    public void setTipo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.Notificaciones.tipo</code>.
     */
    public Integer getTipo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>oko.Notificaciones.nuevoOKOID</code>.
     */
    public void setNuevookoid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.Notificaciones.nuevoOKOID</code>.
     */
    public Integer getNuevookoid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>oko.Notificaciones.fechaInsert</code>.
     */
    public void setFechainsert(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.Notificaciones.fechaInsert</code>.
     */
    public Timestamp getFechainsert() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>oko.Notificaciones.idUsuarioEmisor</code>.
     */
    public void setIdusuarioemisor(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.Notificaciones.idUsuarioEmisor</code>.
     */
    public Integer getIdusuarioemisor() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>oko.Notificaciones.idUsuarioReceptor</code>.
     */
    public void setIdusuarioreceptor(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>oko.Notificaciones.idUsuarioReceptor</code>.
     */
    public Integer getIdusuarioreceptor() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Timestamp, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Timestamp, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Notificaciones.NOTIFICACIONES.IDNOTIFICACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Notificaciones.NOTIFICACIONES.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Notificaciones.NOTIFICACIONES.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Notificaciones.NOTIFICACIONES.NUEVOOKOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Notificaciones.NOTIFICACIONES.FECHAINSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Notificaciones.NOTIFICACIONES.IDUSUARIOEMISOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Notificaciones.NOTIFICACIONES.IDUSUARIORECEPTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdnotificacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNuevookoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFechainsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIdusuarioemisor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdusuarioreceptor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionesRecord value1(Integer value) {
        setIdnotificacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionesRecord value2(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionesRecord value3(Integer value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionesRecord value4(Integer value) {
        setNuevookoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionesRecord value5(Timestamp value) {
        setFechainsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionesRecord value6(Integer value) {
        setIdusuarioemisor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionesRecord value7(Integer value) {
        setIdusuarioreceptor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificacionesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificacionesRecord
     */
    public NotificacionesRecord() {
        super(Notificaciones.NOTIFICACIONES);
    }

    /**
     * Create a detached, initialised NotificacionesRecord
     */
    public NotificacionesRecord(Integer idnotificacion, Integer status, Integer tipo, Integer nuevookoid, Timestamp fechainsert, Integer idusuarioemisor, Integer idusuarioreceptor) {
        super(Notificaciones.NOTIFICACIONES);

        set(0, idnotificacion);
        set(1, status);
        set(2, tipo);
        set(3, nuevookoid);
        set(4, fechainsert);
        set(5, idusuarioemisor);
        set(6, idusuarioreceptor);
    }
}
