/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Numerosserie;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NumerosserieRecord extends UpdatableRecordImpl<NumerosserieRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -336944672;

    /**
     * Setter for <code>oko.NumerosSerie.idNumeroSerie</code>.
     */
    public void setIdnumeroserie(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.NumerosSerie.idNumeroSerie</code>.
     */
    public Integer getIdnumeroserie() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.NumerosSerie.NumeroSerie</code>.
     */
    public void setNumeroserie(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.NumerosSerie.NumeroSerie</code>.
     */
    public String getNumeroserie() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.NumerosSerie.Activo</code>.
     */
    public void setActivo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.NumerosSerie.Activo</code>.
     */
    public Integer getActivo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>oko.NumerosSerie.idEmpresa</code>.
     */
    public void setIdempresa(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.NumerosSerie.idEmpresa</code>.
     */
    public Integer getIdempresa() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Numerosserie.NUMEROSSERIE.IDNUMEROSERIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Numerosserie.NUMEROSSERIE.NUMEROSERIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Numerosserie.NUMEROSSERIE.ACTIVO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Numerosserie.NUMEROSSERIE.IDEMPRESA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdnumeroserie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumeroserie();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getActivo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdempresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumerosserieRecord value1(Integer value) {
        setIdnumeroserie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumerosserieRecord value2(String value) {
        setNumeroserie(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumerosserieRecord value3(Integer value) {
        setActivo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumerosserieRecord value4(Integer value) {
        setIdempresa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NumerosserieRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NumerosserieRecord
     */
    public NumerosserieRecord() {
        super(Numerosserie.NUMEROSSERIE);
    }

    /**
     * Create a detached, initialised NumerosserieRecord
     */
    public NumerosserieRecord(Integer idnumeroserie, String numeroserie, Integer activo, Integer idempresa) {
        super(Numerosserie.NUMEROSSERIE);

        set(0, idnumeroserie);
        set(1, numeroserie);
        set(2, activo);
        set(3, idempresa);
    }
}
