/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Usuarioscontactos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioscontactosRecord extends UpdatableRecordImpl<UsuarioscontactosRecord> implements Record5<Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -816804284;

    /**
     * Setter for <code>oko.UsuariosContactos.idUsuariosContactos</code>.
     */
    public void setIdusuarioscontactos(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.UsuariosContactos.idUsuariosContactos</code>.
     */
    public Integer getIdusuarioscontactos() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.UsuariosContactos.estado</code>.
     */
    public void setEstado(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.UsuariosContactos.estado</code>.
     */
    public Integer getEstado() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>oko.UsuariosContactos.telefoo</code>.
     */
    public void setTelefoo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.UsuariosContactos.telefoo</code>.
     */
    public String getTelefoo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.UsuariosContactos.idUsuario</code>.
     */
    public void setIdusuario(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.UsuariosContactos.idUsuario</code>.
     */
    public Integer getIdusuario() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>oko.UsuariosContactos.idUsuarioContacto</code>.
     */
    public void setIdusuariocontacto(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.UsuariosContactos.idUsuarioContacto</code>.
     */
    public Integer getIdusuariocontacto() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usuarioscontactos.USUARIOSCONTACTOS.IDUSUARIOSCONTACTOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Usuarioscontactos.USUARIOSCONTACTOS.ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Usuarioscontactos.USUARIOSCONTACTOS.TELEFOO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Usuarioscontactos.USUARIOSCONTACTOS.IDUSUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Usuarioscontactos.USUARIOSCONTACTOS.IDUSUARIOCONTACTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdusuarioscontactos();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTelefoo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdusuariocontacto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioscontactosRecord value1(Integer value) {
        setIdusuarioscontactos(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioscontactosRecord value2(Integer value) {
        setEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioscontactosRecord value3(String value) {
        setTelefoo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioscontactosRecord value4(Integer value) {
        setIdusuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioscontactosRecord value5(Integer value) {
        setIdusuariocontacto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioscontactosRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioscontactosRecord
     */
    public UsuarioscontactosRecord() {
        super(Usuarioscontactos.USUARIOSCONTACTOS);
    }

    /**
     * Create a detached, initialised UsuarioscontactosRecord
     */
    public UsuarioscontactosRecord(Integer idusuarioscontactos, Integer estado, String telefoo, Integer idusuario, Integer idusuariocontacto) {
        super(Usuarioscontactos.USUARIOSCONTACTOS);

        set(0, idusuarioscontactos);
        set(1, estado);
        set(2, telefoo);
        set(3, idusuario);
        set(4, idusuariocontacto);
    }
}
