/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Usuarios;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuariosRecord extends UpdatableRecordImpl<UsuariosRecord> implements Record14<Integer, String, String, String, String, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1006860289;

    /**
     * Setter for <code>oko.Usuarios.idUsuario</code>.
     */
    public void setIdusuario(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.Usuarios.idUsuario</code>.
     */
    public Integer getIdusuario() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.Usuarios.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.Usuarios.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.Usuarios.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.Usuarios.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.Usuarios.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.Usuarios.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oko.Usuarios.pwd</code>.
     */
    public void setPwd(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.Usuarios.pwd</code>.
     */
    public String getPwd() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oko.Usuarios.salt</code>.
     */
    public void setSalt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.Usuarios.salt</code>.
     */
    public String getSalt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oko.Usuarios.urlAvatar</code>.
     */
    public void setUrlavatar(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oko.Usuarios.urlAvatar</code>.
     */
    public String getUrlavatar() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oko.Usuarios.apiKey</code>.
     */
    public void setApikey(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oko.Usuarios.apiKey</code>.
     */
    public String getApikey() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oko.Usuarios.userGuid</code>.
     */
    public void setUserguid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>oko.Usuarios.userGuid</code>.
     */
    public String getUserguid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>oko.Usuarios.idioma</code>.
     */
    public void setIdioma(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>oko.Usuarios.idioma</code>.
     */
    public String getIdioma() {
        return (String) get(9);
    }

    /**
     * Setter for <code>oko.Usuarios.emailValidado</code>.
     */
    public void setEmailvalidado(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>oko.Usuarios.emailValidado</code>.
     */
    public Integer getEmailvalidado() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>oko.Usuarios.telefonoValidado</code>.
     */
    public void setTelefonovalidado(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>oko.Usuarios.telefonoValidado</code>.
     */
    public Integer getTelefonovalidado() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>oko.Usuarios.lastLogin</code>.
     */
    public void setLastlogin(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>oko.Usuarios.lastLogin</code>.
     */
    public Timestamp getLastlogin() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>oko.Usuarios.fechaInsert</code>.
     */
    public void setFechainsert(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>oko.Usuarios.fechaInsert</code>.
     */
    public Timestamp getFechainsert() {
        return (Timestamp) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, String, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, String, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usuarios.USUARIOS.IDUSUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Usuarios.USUARIOS.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Usuarios.USUARIOS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Usuarios.USUARIOS.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Usuarios.USUARIOS.PWD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Usuarios.USUARIOS.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Usuarios.USUARIOS.URLAVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Usuarios.USUARIOS.APIKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Usuarios.USUARIOS.USERGUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Usuarios.USUARIOS.IDIOMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Usuarios.USUARIOS.EMAILVALIDADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Usuarios.USUARIOS.TELEFONOVALIDADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Usuarios.USUARIOS.LASTLOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return Usuarios.USUARIOS.FECHAINSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPwd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUrlavatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getApikey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUserguid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getIdioma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getEmailvalidado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getTelefonovalidado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getLastlogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getFechainsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value1(Integer value) {
        setIdusuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value4(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value5(String value) {
        setPwd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value6(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value7(String value) {
        setUrlavatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value8(String value) {
        setApikey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value9(String value) {
        setUserguid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value10(String value) {
        setIdioma(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value11(Integer value) {
        setEmailvalidado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value12(Integer value) {
        setTelefonovalidado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value13(Timestamp value) {
        setLastlogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value14(Timestamp value) {
        setFechainsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Integer value11, Integer value12, Timestamp value13, Timestamp value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuariosRecord
     */
    public UsuariosRecord() {
        super(Usuarios.USUARIOS);
    }

    /**
     * Create a detached, initialised UsuariosRecord
     */
    public UsuariosRecord(Integer idusuario, String nombre, String email, String telefono, String pwd, String salt, String urlavatar, String apikey, String userguid, String idioma, Integer emailvalidado, Integer telefonovalidado, Timestamp lastlogin, Timestamp fechainsert) {
        super(Usuarios.USUARIOS);

        set(0, idusuario);
        set(1, nombre);
        set(2, email);
        set(3, telefono);
        set(4, pwd);
        set(5, salt);
        set(6, urlavatar);
        set(7, apikey);
        set(8, userguid);
        set(9, idioma);
        set(10, emailvalidado);
        set(11, telefonovalidado);
        set(12, lastlogin);
        set(13, fechainsert);
    }
}
