/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Usuariosadmin;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuariosadminRecord extends UpdatableRecordImpl<UsuariosadminRecord> implements Record8<Integer, String, String, String, Timestamp, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = -1582499927;

    /**
     * Setter for <code>oko.UsuariosAdmin.idUsuariosAdmin</code>.
     */
    public void setIdusuariosadmin(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdmin.idUsuariosAdmin</code>.
     */
    public Integer getIdusuariosadmin() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.UsuariosAdmin.login</code>.
     */
    public void setLogin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdmin.login</code>.
     */
    public String getLogin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oko.UsuariosAdmin.pwd</code>.
     */
    public void setPwd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdmin.pwd</code>.
     */
    public String getPwd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oko.UsuariosAdmin.salt</code>.
     */
    public void setSalt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdmin.salt</code>.
     */
    public String getSalt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oko.UsuariosAdmin.fechaInsert</code>.
     */
    public void setFechainsert(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdmin.fechaInsert</code>.
     */
    public Timestamp getFechainsert() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>oko.UsuariosAdmin.rol</code>.
     */
    public void setRol(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdmin.rol</code>.
     */
    public Integer getRol() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>oko.UsuariosAdmin.lastLogin</code>.
     */
    public void setLastlogin(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdmin.lastLogin</code>.
     */
    public Timestamp getLastlogin() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>oko.UsuariosAdmin.idEmpresa</code>.
     */
    public void setIdempresa(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdmin.idEmpresa</code>.
     */
    public Integer getIdempresa() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Timestamp, Integer, Timestamp, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Timestamp, Integer, Timestamp, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usuariosadmin.USUARIOSADMIN.IDUSUARIOSADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Usuariosadmin.USUARIOSADMIN.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Usuariosadmin.USUARIOSADMIN.PWD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Usuariosadmin.USUARIOSADMIN.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Usuariosadmin.USUARIOSADMIN.FECHAINSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Usuariosadmin.USUARIOSADMIN.ROL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Usuariosadmin.USUARIOSADMIN.LASTLOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Usuariosadmin.USUARIOSADMIN.IDEMPRESA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdusuariosadmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPwd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFechainsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getRol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastlogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdempresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord value1(Integer value) {
        setIdusuariosadmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord value2(String value) {
        setLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord value3(String value) {
        setPwd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord value4(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord value5(Timestamp value) {
        setFechainsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord value6(Integer value) {
        setRol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord value7(Timestamp value) {
        setLastlogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord value8(Integer value) {
        setIdempresa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Integer value6, Timestamp value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuariosadminRecord
     */
    public UsuariosadminRecord() {
        super(Usuariosadmin.USUARIOSADMIN);
    }

    /**
     * Create a detached, initialised UsuariosadminRecord
     */
    public UsuariosadminRecord(Integer idusuariosadmin, String login, String pwd, String salt, Timestamp fechainsert, Integer rol, Timestamp lastlogin, Integer idempresa) {
        super(Usuariosadmin.USUARIOSADMIN);

        set(0, idusuariosadmin);
        set(1, login);
        set(2, pwd);
        set(3, salt);
        set(4, fechainsert);
        set(5, rol);
        set(6, lastlogin);
        set(7, idempresa);
    }
}
