/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Usuariosadminlocalizaciones;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuariosadminlocalizacionesRecord extends UpdatableRecordImpl<UsuariosadminlocalizacionesRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1463813268;

    /**
     * Setter for <code>oko.UsuariosAdminLocalizaciones.idUsuarioAdminLocalizacion</code>.
     */
    public void setIdusuarioadminlocalizacion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdminLocalizaciones.idUsuarioAdminLocalizacion</code>.
     */
    public Integer getIdusuarioadminlocalizacion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.UsuariosAdminLocalizaciones.idUsuarioAdmin</code>.
     */
    public void setIdusuarioadmin(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdminLocalizaciones.idUsuarioAdmin</code>.
     */
    public Integer getIdusuarioadmin() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>oko.UsuariosAdminLocalizaciones.idLocalizacion</code>.
     */
    public void setIdlocalizacion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.UsuariosAdminLocalizaciones.idLocalizacion</code>.
     */
    public Integer getIdlocalizacion() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDUSUARIOADMINLOCALIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDUSUARIOADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDLOCALIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdusuarioadminlocalizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdusuarioadmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdlocalizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminlocalizacionesRecord value1(Integer value) {
        setIdusuarioadminlocalizacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminlocalizacionesRecord value2(Integer value) {
        setIdusuarioadmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminlocalizacionesRecord value3(Integer value) {
        setIdlocalizacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosadminlocalizacionesRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuariosadminlocalizacionesRecord
     */
    public UsuariosadminlocalizacionesRecord() {
        super(Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES);
    }

    /**
     * Create a detached, initialised UsuariosadminlocalizacionesRecord
     */
    public UsuariosadminlocalizacionesRecord(Integer idusuarioadminlocalizacion, Integer idusuarioadmin, Integer idlocalizacion) {
        super(Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES);

        set(0, idusuarioadminlocalizacion);
        set(1, idusuarioadmin);
        set(2, idlocalizacion);
    }
}
