/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables.records;


import com.cimne.tic.oko.server.ws.model.tables.Usuariosdispositivosvirtuales;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuariosdispositivosvirtualesRecord extends UpdatableRecordImpl<UsuariosdispositivosvirtualesRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -163464153;

    /**
     * Setter for <code>oko.UsuariosDispositivosVirtuales.idUsuariosDispositivosVirtual</code>.
     */
    public void setIdusuariosdispositivosvirtual(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>oko.UsuariosDispositivosVirtuales.idUsuariosDispositivosVirtual</code>.
     */
    public Integer getIdusuariosdispositivosvirtual() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>oko.UsuariosDispositivosVirtuales.rol</code>.
     */
    public void setRol(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>oko.UsuariosDispositivosVirtuales.rol</code>.
     */
    public Integer getRol() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>oko.UsuariosDispositivosVirtuales.idUsuario</code>.
     */
    public void setIdusuario(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>oko.UsuariosDispositivosVirtuales.idUsuario</code>.
     */
    public Integer getIdusuario() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>oko.UsuariosDispositivosVirtuales.idDispositivoVirtual</code>.
     */
    public void setIddispositivovirtual(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>oko.UsuariosDispositivosVirtuales.idDispositivoVirtual</code>.
     */
    public Integer getIddispositivovirtual() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDUSUARIOSDISPOSITIVOSVIRTUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.ROL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDUSUARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDDISPOSITIVOVIRTUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdusuariosdispositivosvirtual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIddispositivovirtual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosdispositivosvirtualesRecord value1(Integer value) {
        setIdusuariosdispositivosvirtual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosdispositivosvirtualesRecord value2(Integer value) {
        setRol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosdispositivosvirtualesRecord value3(Integer value) {
        setIdusuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosdispositivosvirtualesRecord value4(Integer value) {
        setIddispositivovirtual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosdispositivosvirtualesRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuariosdispositivosvirtualesRecord
     */
    public UsuariosdispositivosvirtualesRecord() {
        super(Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES);
    }

    /**
     * Create a detached, initialised UsuariosdispositivosvirtualesRecord
     */
    public UsuariosdispositivosvirtualesRecord(Integer idusuariosdispositivosvirtual, Integer rol, Integer idusuario, Integer iddispositivovirtual) {
        super(Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES);

        set(0, idusuariosdispositivosvirtual);
        set(1, rol);
        set(2, idusuario);
        set(3, iddispositivovirtual);
    }
}
