/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables;


import com.cimne.tic.oko.server.ws.model.Keys;
import com.cimne.tic.oko.server.ws.model.Oko;
import com.cimne.tic.oko.server.ws.model.tables.records.ActualizacionesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Actualizaciones extends TableImpl<ActualizacionesRecord> {

    private static final long serialVersionUID = 610947489;

    /**
     * The reference instance of <code>oko.Actualizaciones</code>
     */
    public static final Actualizaciones ACTUALIZACIONES = new Actualizaciones();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActualizacionesRecord> getRecordType() {
        return ActualizacionesRecord.class;
    }

    /**
     * The column <code>oko.Actualizaciones.idActualizacion</code>.
     */
    public final TableField<ActualizacionesRecord, Integer> IDACTUALIZACION = createField("idActualizacion", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.nombre</code>.
     */
    public final TableField<ActualizacionesRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>oko.Actualizaciones.pathUpdate</code>.
     */
    public final TableField<ActualizacionesRecord, String> PATHUPDATE = createField("pathUpdate", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.changeLog</code>.
     */
    public final TableField<ActualizacionesRecord, String> CHANGELOG = createField("changeLog", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

    /**
     * The column <code>oko.Actualizaciones.md5hash</code>.
     */
    public final TableField<ActualizacionesRecord, String> MD5HASH = createField("md5hash", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.versionCode</code>.
     */
    public final TableField<ActualizacionesRecord, Integer> VERSIONCODE = createField("versionCode", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.versionName</code>.
     */
    public final TableField<ActualizacionesRecord, String> VERSIONNAME = createField("versionName", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.versionNameUpdater</code>.
     */
    public final TableField<ActualizacionesRecord, String> VERSIONNAMEUPDATER = createField("versionNameUpdater", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.permitirActualizar</code>.
     */
    public final TableField<ActualizacionesRecord, Integer> PERMITIRACTUALIZAR = createField("permitirActualizar", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.tipo</code>.
     */
    public final TableField<ActualizacionesRecord, Integer> TIPO = createField("tipo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.fechaPublicado</code>.
     */
    public final TableField<ActualizacionesRecord, Timestamp> FECHAPUBLICADO = createField("fechaPublicado", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>oko.Actualizaciones.fechaInsert</code>.
     */
    public final TableField<ActualizacionesRecord, Timestamp> FECHAINSERT = createField("fechaInsert", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>oko.Actualizaciones</code> table reference
     */
    public Actualizaciones() {
        this("Actualizaciones", null);
    }

    /**
     * Create an aliased <code>oko.Actualizaciones</code> table reference
     */
    public Actualizaciones(String alias) {
        this(alias, ACTUALIZACIONES);
    }

    private Actualizaciones(String alias, Table<ActualizacionesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Actualizaciones(String alias, Table<ActualizacionesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Oko.OKO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ActualizacionesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ACTUALIZACIONES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ActualizacionesRecord> getPrimaryKey() {
        return Keys.KEY_ACTUALIZACIONES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ActualizacionesRecord>> getKeys() {
        return Arrays.<UniqueKey<ActualizacionesRecord>>asList(Keys.KEY_ACTUALIZACIONES_PRIMARY, Keys.KEY_ACTUALIZACIONES_IDACTUALIZACION_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Actualizaciones as(String alias) {
        return new Actualizaciones(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Actualizaciones rename(String name) {
        return new Actualizaciones(name, null);
    }
}
