/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables;


import com.cimne.tic.oko.server.ws.model.Keys;
import com.cimne.tic.oko.server.ws.model.Oko;
import com.cimne.tic.oko.server.ws.model.tables.records.ContenidosinicialesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contenidosiniciales extends TableImpl<ContenidosinicialesRecord> {

    private static final long serialVersionUID = 1931256355;

    /**
     * The reference instance of <code>oko.ContenidosIniciales</code>
     */
    public static final Contenidosiniciales CONTENIDOSINICIALES = new Contenidosiniciales();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContenidosinicialesRecord> getRecordType() {
        return ContenidosinicialesRecord.class;
    }

    /**
     * The column <code>oko.ContenidosIniciales.idContenidoInicial</code>.
     */
    public final TableField<ContenidosinicialesRecord, Integer> IDCONTENIDOINICIAL = createField("idContenidoInicial", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.ContenidosIniciales.url</code>.
     */
    public final TableField<ContenidosinicialesRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>oko.ContenidosIniciales.texto</code>.
     */
    public final TableField<ContenidosinicialesRecord, String> TEXTO = createField("texto", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>oko.ContenidosIniciales.tipo</code>.
     */
    public final TableField<ContenidosinicialesRecord, Integer> TIPO = createField("tipo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.ContenidosIniciales.idLocalizacion</code>.
     */
    public final TableField<ContenidosinicialesRecord, Integer> IDLOCALIZACION = createField("idLocalizacion", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>oko.ContenidosIniciales</code> table reference
     */
    public Contenidosiniciales() {
        this("ContenidosIniciales", null);
    }

    /**
     * Create an aliased <code>oko.ContenidosIniciales</code> table reference
     */
    public Contenidosiniciales(String alias) {
        this(alias, CONTENIDOSINICIALES);
    }

    private Contenidosiniciales(String alias, Table<ContenidosinicialesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Contenidosiniciales(String alias, Table<ContenidosinicialesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Oko.OKO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContenidosinicialesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CONTENIDOSINICIALES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContenidosinicialesRecord> getPrimaryKey() {
        return Keys.KEY_CONTENIDOSINICIALES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContenidosinicialesRecord>> getKeys() {
        return Arrays.<UniqueKey<ContenidosinicialesRecord>>asList(Keys.KEY_CONTENIDOSINICIALES_PRIMARY, Keys.KEY_CONTENIDOSINICIALES_IDCONTENIDOINICIAL_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContenidosinicialesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContenidosinicialesRecord, ?>>asList(Keys.FK_CONTENIDOSINICIALES_LOCALIZACIONES1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Contenidosiniciales as(String alias) {
        return new Contenidosiniciales(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Contenidosiniciales rename(String name) {
        return new Contenidosiniciales(name, null);
    }
}
