/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables;


import com.cimne.tic.oko.server.ws.model.Keys;
import com.cimne.tic.oko.server.ws.model.Oko;
import com.cimne.tic.oko.server.ws.model.tables.records.ContenidosfisicosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contenidosfisicos extends TableImpl<ContenidosfisicosRecord> {

    private static final long serialVersionUID = -2077571107;

    /**
     * The reference instance of <code>oko.ContenidosFisicos</code>
     */
    public static final Contenidosfisicos CONTENIDOSFISICOS = new Contenidosfisicos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContenidosfisicosRecord> getRecordType() {
        return ContenidosfisicosRecord.class;
    }

    /**
     * The column <code>oko.ContenidosFisicos.idContenidoFisico</code>.
     */
    public final TableField<ContenidosfisicosRecord, Integer> IDCONTENIDOFISICO = createField("idContenidoFisico", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.ContenidosFisicos.pathContenidoFisico</code>.
     */
    public final TableField<ContenidosfisicosRecord, String> PATHCONTENIDOFISICO = createField("pathContenidoFisico", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

    /**
     * The column <code>oko.ContenidosFisicos.pathThumbnail</code>.
     */
    public final TableField<ContenidosfisicosRecord, String> PATHTHUMBNAIL = createField("pathThumbnail", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

    /**
     * Create a <code>oko.ContenidosFisicos</code> table reference
     */
    public Contenidosfisicos() {
        this("ContenidosFisicos", null);
    }

    /**
     * Create an aliased <code>oko.ContenidosFisicos</code> table reference
     */
    public Contenidosfisicos(String alias) {
        this(alias, CONTENIDOSFISICOS);
    }

    private Contenidosfisicos(String alias, Table<ContenidosfisicosRecord> aliased) {
        this(alias, aliased, null);
    }

    private Contenidosfisicos(String alias, Table<ContenidosfisicosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Oko.OKO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ContenidosfisicosRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CONTENIDOSFISICOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContenidosfisicosRecord> getPrimaryKey() {
        return Keys.KEY_CONTENIDOSFISICOS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContenidosfisicosRecord>> getKeys() {
        return Arrays.<UniqueKey<ContenidosfisicosRecord>>asList(Keys.KEY_CONTENIDOSFISICOS_PRIMARY, Keys.KEY_CONTENIDOSFISICOS_IDCONTENIDOFISICO_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Contenidosfisicos as(String alias) {
        return new Contenidosfisicos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Contenidosfisicos rename(String name) {
        return new Contenidosfisicos(name, null);
    }
}
