/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables;


import com.cimne.tic.oko.server.ws.model.Keys;
import com.cimne.tic.oko.server.ws.model.Oko;
import com.cimne.tic.oko.server.ws.model.tables.records.EstadocontenidomultimediaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Estadocontenidomultimedia extends TableImpl<EstadocontenidomultimediaRecord> {

    private static final long serialVersionUID = -367069614;

    /**
     * The reference instance of <code>oko.EstadoContenidoMultimedia</code>
     */
    public static final Estadocontenidomultimedia ESTADOCONTENIDOMULTIMEDIA = new Estadocontenidomultimedia();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EstadocontenidomultimediaRecord> getRecordType() {
        return EstadocontenidomultimediaRecord.class;
    }

    /**
     * The column <code>oko.EstadoContenidoMultimedia.idEstadoContenidoMultimedia</code>.
     */
    public final TableField<EstadocontenidomultimediaRecord, Integer> IDESTADOCONTENIDOMULTIMEDIA = createField("idEstadoContenidoMultimedia", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.EstadoContenidoMultimedia.estado</code>.
     */
    public final TableField<EstadocontenidomultimediaRecord, Integer> ESTADO = createField("estado", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.EstadoContenidoMultimedia.feedback</code>.
     */
    public final TableField<EstadocontenidomultimediaRecord, Integer> FEEDBACK = createField("feedback", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>oko.EstadoContenidoMultimedia.idMessage</code>.
     */
    public final TableField<EstadocontenidomultimediaRecord, String> IDMESSAGE = createField("idMessage", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

    /**
     * The column <code>oko.EstadoContenidoMultimedia.idContenidoMultimedia</code>.
     */
    public final TableField<EstadocontenidomultimediaRecord, Integer> IDCONTENIDOMULTIMEDIA = createField("idContenidoMultimedia", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.EstadoContenidoMultimedia.idDispositivoVirtual</code>.
     */
    public final TableField<EstadocontenidomultimediaRecord, Integer> IDDISPOSITIVOVIRTUAL = createField("idDispositivoVirtual", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>oko.EstadoContenidoMultimedia</code> table reference
     */
    public Estadocontenidomultimedia() {
        this("EstadoContenidoMultimedia", null);
    }

    /**
     * Create an aliased <code>oko.EstadoContenidoMultimedia</code> table reference
     */
    public Estadocontenidomultimedia(String alias) {
        this(alias, ESTADOCONTENIDOMULTIMEDIA);
    }

    private Estadocontenidomultimedia(String alias, Table<EstadocontenidomultimediaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Estadocontenidomultimedia(String alias, Table<EstadocontenidomultimediaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Oko.OKO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EstadocontenidomultimediaRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ESTADOCONTENIDOMULTIMEDIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EstadocontenidomultimediaRecord> getPrimaryKey() {
        return Keys.KEY_ESTADOCONTENIDOMULTIMEDIA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EstadocontenidomultimediaRecord>> getKeys() {
        return Arrays.<UniqueKey<EstadocontenidomultimediaRecord>>asList(Keys.KEY_ESTADOCONTENIDOMULTIMEDIA_PRIMARY, Keys.KEY_ESTADOCONTENIDOMULTIMEDIA_IDESTADOCONTENIDOMULTIMEDIA_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EstadocontenidomultimediaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EstadocontenidomultimediaRecord, ?>>asList(Keys.FK_CONTENIDOMULTIMEDIAESTADO, Keys.FK_DISPOSITIVOVIRTUALESTADO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Estadocontenidomultimedia as(String alias) {
        return new Estadocontenidomultimedia(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Estadocontenidomultimedia rename(String name) {
        return new Estadocontenidomultimedia(name, null);
    }
}
