/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables;


import com.cimne.tic.oko.server.ws.model.Keys;
import com.cimne.tic.oko.server.ws.model.Oko;
import com.cimne.tic.oko.server.ws.model.tables.records.NumerosserieRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Numerosserie extends TableImpl<NumerosserieRecord> {

    private static final long serialVersionUID = 637787749;

    /**
     * The reference instance of <code>oko.NumerosSerie</code>
     */
    public static final Numerosserie NUMEROSSERIE = new Numerosserie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NumerosserieRecord> getRecordType() {
        return NumerosserieRecord.class;
    }

    /**
     * The column <code>oko.NumerosSerie.idNumeroSerie</code>.
     */
    public final TableField<NumerosserieRecord, Integer> IDNUMEROSERIE = createField("idNumeroSerie", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.NumerosSerie.NumeroSerie</code>.
     */
    public final TableField<NumerosserieRecord, String> NUMEROSERIE = createField("NumeroSerie", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>oko.NumerosSerie.Activo</code>.
     */
    public final TableField<NumerosserieRecord, Integer> ACTIVO = createField("Activo", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>oko.NumerosSerie.idEmpresa</code>.
     */
    public final TableField<NumerosserieRecord, Integer> IDEMPRESA = createField("idEmpresa", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>oko.NumerosSerie</code> table reference
     */
    public Numerosserie() {
        this("NumerosSerie", null);
    }

    /**
     * Create an aliased <code>oko.NumerosSerie</code> table reference
     */
    public Numerosserie(String alias) {
        this(alias, NUMEROSSERIE);
    }

    private Numerosserie(String alias, Table<NumerosserieRecord> aliased) {
        this(alias, aliased, null);
    }

    private Numerosserie(String alias, Table<NumerosserieRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Oko.OKO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<NumerosserieRecord, Integer> getIdentity() {
        return Keys.IDENTITY_NUMEROSSERIE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<NumerosserieRecord> getPrimaryKey() {
        return Keys.KEY_NUMEROSSERIE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<NumerosserieRecord>> getKeys() {
        return Arrays.<UniqueKey<NumerosserieRecord>>asList(Keys.KEY_NUMEROSSERIE_PRIMARY, Keys.KEY_NUMEROSSERIE_IDNUMEROSERIE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<NumerosserieRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<NumerosserieRecord, ?>>asList(Keys.FK_EMPRESA_NUMSERIE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Numerosserie as(String alias) {
        return new Numerosserie(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Numerosserie rename(String name) {
        return new Numerosserie(name, null);
    }
}
