/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model.tables;


import com.cimne.tic.oko.server.ws.model.Keys;
import com.cimne.tic.oko.server.ws.model.Oko;
import com.cimne.tic.oko.server.ws.model.tables.records.SmartphonesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Smartphones extends TableImpl<SmartphonesRecord> {

    private static final long serialVersionUID = 1849205327;

    /**
     * The reference instance of <code>oko.SmartPhones</code>
     */
    public static final Smartphones SMARTPHONES = new Smartphones();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SmartphonesRecord> getRecordType() {
        return SmartphonesRecord.class;
    }

    /**
     * The column <code>oko.SmartPhones.idSmartPhone</code>.
     */
    public final TableField<SmartphonesRecord, Integer> IDSMARTPHONE = createField("idSmartPhone", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.SmartPhones.token</code>.
     */
    public final TableField<SmartphonesRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

    /**
     * The column <code>oko.SmartPhones.tipo</code>.
     */
    public final TableField<SmartphonesRecord, Integer> TIPO = createField("tipo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>oko.SmartPhones.version</code>.
     */
    public final TableField<SmartphonesRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>oko.SmartPhones.fechaInsert</code>.
     */
    public final TableField<SmartphonesRecord, Timestamp> FECHAINSERT = createField("fechaInsert", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>oko.SmartPhones.idUsuario</code>.
     */
    public final TableField<SmartphonesRecord, Integer> IDUSUARIO = createField("idUsuario", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>oko.SmartPhones</code> table reference
     */
    public Smartphones() {
        this("SmartPhones", null);
    }

    /**
     * Create an aliased <code>oko.SmartPhones</code> table reference
     */
    public Smartphones(String alias) {
        this(alias, SMARTPHONES);
    }

    private Smartphones(String alias, Table<SmartphonesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Smartphones(String alias, Table<SmartphonesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Oko.OKO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SmartphonesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SMARTPHONES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SmartphonesRecord> getPrimaryKey() {
        return Keys.KEY_SMARTPHONES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SmartphonesRecord>> getKeys() {
        return Arrays.<UniqueKey<SmartphonesRecord>>asList(Keys.KEY_SMARTPHONES_PRIMARY, Keys.KEY_SMARTPHONES_IDSMARTPHONE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SmartphonesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SmartphonesRecord, ?>>asList(Keys.FK_USUARIOSMARTPHONE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Smartphones as(String alias) {
        return new Smartphones(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Smartphones rename(String name) {
        return new Smartphones(name, null);
    }
}
