/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model;


import com.cimne.tic.oko.server.ws.model.tables.Actualizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Canales;
import com.cimne.tic.oko.server.ws.model.tables.Contenidocanal;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosfisicos;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosiniciales;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosmultimedia;
import com.cimne.tic.oko.server.ws.model.tables.Dispositivosfisicos;
import com.cimne.tic.oko.server.ws.model.tables.Dispositivosvirtuales;
import com.cimne.tic.oko.server.ws.model.tables.Empresa;
import com.cimne.tic.oko.server.ws.model.tables.Estadocontenidomultimedia;
import com.cimne.tic.oko.server.ws.model.tables.Localizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Notificaciones;
import com.cimne.tic.oko.server.ws.model.tables.Notificacionespush;
import com.cimne.tic.oko.server.ws.model.tables.Numerosserie;
import com.cimne.tic.oko.server.ws.model.tables.Smartphones;
import com.cimne.tic.oko.server.ws.model.tables.Usuarios;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosadmin;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosadminlocalizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Usuarioscontactos;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosdispositivosvirtuales;
import com.cimne.tic.oko.server.ws.model.tables.records.ActualizacionesRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.CanalesRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.ContenidocanalRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.ContenidosfisicosRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.ContenidosinicialesRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.ContenidosmultimediaRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.DispositivosfisicosRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.DispositivosvirtualesRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.EmpresaRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.EstadocontenidomultimediaRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.LocalizacionesRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.NotificacionesRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.NotificacionespushRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.NumerosserieRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.SmartphonesRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.UsuariosRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.UsuariosadminRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.UsuariosadminlocalizacionesRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.UsuarioscontactosRecord;
import com.cimne.tic.oko.server.ws.model.tables.records.UsuariosdispositivosvirtualesRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>oko</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ActualizacionesRecord, Integer> IDENTITY_ACTUALIZACIONES = Identities0.IDENTITY_ACTUALIZACIONES;
    public static final Identity<CanalesRecord, Integer> IDENTITY_CANALES = Identities0.IDENTITY_CANALES;
    public static final Identity<ContenidocanalRecord, Integer> IDENTITY_CONTENIDOCANAL = Identities0.IDENTITY_CONTENIDOCANAL;
    public static final Identity<ContenidosfisicosRecord, Integer> IDENTITY_CONTENIDOSFISICOS = Identities0.IDENTITY_CONTENIDOSFISICOS;
    public static final Identity<ContenidosinicialesRecord, Integer> IDENTITY_CONTENIDOSINICIALES = Identities0.IDENTITY_CONTENIDOSINICIALES;
    public static final Identity<ContenidosmultimediaRecord, Integer> IDENTITY_CONTENIDOSMULTIMEDIA = Identities0.IDENTITY_CONTENIDOSMULTIMEDIA;
    public static final Identity<DispositivosfisicosRecord, Integer> IDENTITY_DISPOSITIVOSFISICOS = Identities0.IDENTITY_DISPOSITIVOSFISICOS;
    public static final Identity<DispositivosvirtualesRecord, Integer> IDENTITY_DISPOSITIVOSVIRTUALES = Identities0.IDENTITY_DISPOSITIVOSVIRTUALES;
    public static final Identity<EmpresaRecord, Integer> IDENTITY_EMPRESA = Identities0.IDENTITY_EMPRESA;
    public static final Identity<EstadocontenidomultimediaRecord, Integer> IDENTITY_ESTADOCONTENIDOMULTIMEDIA = Identities0.IDENTITY_ESTADOCONTENIDOMULTIMEDIA;
    public static final Identity<LocalizacionesRecord, Integer> IDENTITY_LOCALIZACIONES = Identities0.IDENTITY_LOCALIZACIONES;
    public static final Identity<NotificacionesRecord, Integer> IDENTITY_NOTIFICACIONES = Identities0.IDENTITY_NOTIFICACIONES;
    public static final Identity<NotificacionespushRecord, Integer> IDENTITY_NOTIFICACIONESPUSH = Identities0.IDENTITY_NOTIFICACIONESPUSH;
    public static final Identity<NumerosserieRecord, Integer> IDENTITY_NUMEROSSERIE = Identities0.IDENTITY_NUMEROSSERIE;
    public static final Identity<SmartphonesRecord, Integer> IDENTITY_SMARTPHONES = Identities0.IDENTITY_SMARTPHONES;
    public static final Identity<UsuariosRecord, Integer> IDENTITY_USUARIOS = Identities0.IDENTITY_USUARIOS;
    public static final Identity<UsuariosadminRecord, Integer> IDENTITY_USUARIOSADMIN = Identities0.IDENTITY_USUARIOSADMIN;
    public static final Identity<UsuariosadminlocalizacionesRecord, Integer> IDENTITY_USUARIOSADMINLOCALIZACIONES = Identities0.IDENTITY_USUARIOSADMINLOCALIZACIONES;
    public static final Identity<UsuarioscontactosRecord, Integer> IDENTITY_USUARIOSCONTACTOS = Identities0.IDENTITY_USUARIOSCONTACTOS;
    public static final Identity<UsuariosdispositivosvirtualesRecord, Integer> IDENTITY_USUARIOSDISPOSITIVOSVIRTUALES = Identities0.IDENTITY_USUARIOSDISPOSITIVOSVIRTUALES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActualizacionesRecord> KEY_ACTUALIZACIONES_PRIMARY = UniqueKeys0.KEY_ACTUALIZACIONES_PRIMARY;
    public static final UniqueKey<ActualizacionesRecord> KEY_ACTUALIZACIONES_IDACTUALIZACION_UNIQUE = UniqueKeys0.KEY_ACTUALIZACIONES_IDACTUALIZACION_UNIQUE;
    public static final UniqueKey<CanalesRecord> KEY_CANALES_PRIMARY = UniqueKeys0.KEY_CANALES_PRIMARY;
    public static final UniqueKey<CanalesRecord> KEY_CANALES_IDCANAL_UNIQUE = UniqueKeys0.KEY_CANALES_IDCANAL_UNIQUE;
    public static final UniqueKey<ContenidocanalRecord> KEY_CONTENIDOCANAL_PRIMARY = UniqueKeys0.KEY_CONTENIDOCANAL_PRIMARY;
    public static final UniqueKey<ContenidosfisicosRecord> KEY_CONTENIDOSFISICOS_PRIMARY = UniqueKeys0.KEY_CONTENIDOSFISICOS_PRIMARY;
    public static final UniqueKey<ContenidosfisicosRecord> KEY_CONTENIDOSFISICOS_IDCONTENIDOFISICO_UNIQUE = UniqueKeys0.KEY_CONTENIDOSFISICOS_IDCONTENIDOFISICO_UNIQUE;
    public static final UniqueKey<ContenidosinicialesRecord> KEY_CONTENIDOSINICIALES_PRIMARY = UniqueKeys0.KEY_CONTENIDOSINICIALES_PRIMARY;
    public static final UniqueKey<ContenidosinicialesRecord> KEY_CONTENIDOSINICIALES_IDCONTENIDOINICIAL_UNIQUE = UniqueKeys0.KEY_CONTENIDOSINICIALES_IDCONTENIDOINICIAL_UNIQUE;
    public static final UniqueKey<ContenidosmultimediaRecord> KEY_CONTENIDOSMULTIMEDIA_PRIMARY = UniqueKeys0.KEY_CONTENIDOSMULTIMEDIA_PRIMARY;
    public static final UniqueKey<ContenidosmultimediaRecord> KEY_CONTENIDOSMULTIMEDIA_IDCONTENIDOMULTIMEDIA_UNIQUE = UniqueKeys0.KEY_CONTENIDOSMULTIMEDIA_IDCONTENIDOMULTIMEDIA_UNIQUE;
    public static final UniqueKey<DispositivosfisicosRecord> KEY_DISPOSITIVOSFISICOS_PRIMARY = UniqueKeys0.KEY_DISPOSITIVOSFISICOS_PRIMARY;
    public static final UniqueKey<DispositivosfisicosRecord> KEY_DISPOSITIVOSFISICOS_IDDISPOSITIVOSFISICOS_UNIQUE = UniqueKeys0.KEY_DISPOSITIVOSFISICOS_IDDISPOSITIVOSFISICOS_UNIQUE;
    public static final UniqueKey<DispositivosvirtualesRecord> KEY_DISPOSITIVOSVIRTUALES_PRIMARY = UniqueKeys0.KEY_DISPOSITIVOSVIRTUALES_PRIMARY;
    public static final UniqueKey<DispositivosvirtualesRecord> KEY_DISPOSITIVOSVIRTUALES_IDDISPOSITIVOSVIRTUAL_UNIQUE = UniqueKeys0.KEY_DISPOSITIVOSVIRTUALES_IDDISPOSITIVOSVIRTUAL_UNIQUE;
    public static final UniqueKey<DispositivosvirtualesRecord> KEY_DISPOSITIVOSVIRTUALES_UUID_UNIQUE = UniqueKeys0.KEY_DISPOSITIVOSVIRTUALES_UUID_UNIQUE;
    public static final UniqueKey<EmpresaRecord> KEY_EMPRESA_PRIMARY = UniqueKeys0.KEY_EMPRESA_PRIMARY;
    public static final UniqueKey<EmpresaRecord> KEY_EMPRESA_IDEMPRESA_UNIQUE = UniqueKeys0.KEY_EMPRESA_IDEMPRESA_UNIQUE;
    public static final UniqueKey<EstadocontenidomultimediaRecord> KEY_ESTADOCONTENIDOMULTIMEDIA_PRIMARY = UniqueKeys0.KEY_ESTADOCONTENIDOMULTIMEDIA_PRIMARY;
    public static final UniqueKey<EstadocontenidomultimediaRecord> KEY_ESTADOCONTENIDOMULTIMEDIA_IDESTADOCONTENIDOMULTIMEDIA_UNIQUE = UniqueKeys0.KEY_ESTADOCONTENIDOMULTIMEDIA_IDESTADOCONTENIDOMULTIMEDIA_UNIQUE;
    public static final UniqueKey<LocalizacionesRecord> KEY_LOCALIZACIONES_PRIMARY = UniqueKeys0.KEY_LOCALIZACIONES_PRIMARY;
    public static final UniqueKey<LocalizacionesRecord> KEY_LOCALIZACIONES_IDLOCALIZACION_UNIQUE = UniqueKeys0.KEY_LOCALIZACIONES_IDLOCALIZACION_UNIQUE;
    public static final UniqueKey<NotificacionesRecord> KEY_NOTIFICACIONES_PRIMARY = UniqueKeys0.KEY_NOTIFICACIONES_PRIMARY;
    public static final UniqueKey<NotificacionesRecord> KEY_NOTIFICACIONES_IDNOTIFICACION_UNIQUE = UniqueKeys0.KEY_NOTIFICACIONES_IDNOTIFICACION_UNIQUE;
    public static final UniqueKey<NotificacionespushRecord> KEY_NOTIFICACIONESPUSH_PRIMARY = UniqueKeys0.KEY_NOTIFICACIONESPUSH_PRIMARY;
    public static final UniqueKey<NotificacionespushRecord> KEY_NOTIFICACIONESPUSH_IDNOTIFICACIONPUSH_UNIQUE = UniqueKeys0.KEY_NOTIFICACIONESPUSH_IDNOTIFICACIONPUSH_UNIQUE;
    public static final UniqueKey<NotificacionespushRecord> KEY_NOTIFICACIONESPUSH_IDMENSAJE_UNIQUE = UniqueKeys0.KEY_NOTIFICACIONESPUSH_IDMENSAJE_UNIQUE;
    public static final UniqueKey<NumerosserieRecord> KEY_NUMEROSSERIE_PRIMARY = UniqueKeys0.KEY_NUMEROSSERIE_PRIMARY;
    public static final UniqueKey<NumerosserieRecord> KEY_NUMEROSSERIE_IDNUMEROSERIE_UNIQUE = UniqueKeys0.KEY_NUMEROSSERIE_IDNUMEROSERIE_UNIQUE;
    public static final UniqueKey<SmartphonesRecord> KEY_SMARTPHONES_PRIMARY = UniqueKeys0.KEY_SMARTPHONES_PRIMARY;
    public static final UniqueKey<SmartphonesRecord> KEY_SMARTPHONES_IDSMARTPHONE_UNIQUE = UniqueKeys0.KEY_SMARTPHONES_IDSMARTPHONE_UNIQUE;
    public static final UniqueKey<UsuariosRecord> KEY_USUARIOS_PRIMARY = UniqueKeys0.KEY_USUARIOS_PRIMARY;
    public static final UniqueKey<UsuariosRecord> KEY_USUARIOS_IDUSUARIO_UNIQUE = UniqueKeys0.KEY_USUARIOS_IDUSUARIO_UNIQUE;
    public static final UniqueKey<UsuariosRecord> KEY_USUARIOS_EMAIL_UNIQUE = UniqueKeys0.KEY_USUARIOS_EMAIL_UNIQUE;
    public static final UniqueKey<UsuariosRecord> KEY_USUARIOS_TELEFONO_UNIQUE = UniqueKeys0.KEY_USUARIOS_TELEFONO_UNIQUE;
    public static final UniqueKey<UsuariosadminRecord> KEY_USUARIOSADMIN_PRIMARY = UniqueKeys0.KEY_USUARIOSADMIN_PRIMARY;
    public static final UniqueKey<UsuariosadminRecord> KEY_USUARIOSADMIN_IDUSUARIOSADMIN_UNIQUE = UniqueKeys0.KEY_USUARIOSADMIN_IDUSUARIOSADMIN_UNIQUE;
    public static final UniqueKey<UsuariosadminlocalizacionesRecord> KEY_USUARIOSADMINLOCALIZACIONES_PRIMARY = UniqueKeys0.KEY_USUARIOSADMINLOCALIZACIONES_PRIMARY;
    public static final UniqueKey<UsuariosadminlocalizacionesRecord> KEY_USUARIOSADMINLOCALIZACIONES_IDUSUARIOADMINLOCALIZACION_UNIQUE = UniqueKeys0.KEY_USUARIOSADMINLOCALIZACIONES_IDUSUARIOADMINLOCALIZACION_UNIQUE;
    public static final UniqueKey<UsuarioscontactosRecord> KEY_USUARIOSCONTACTOS_PRIMARY = UniqueKeys0.KEY_USUARIOSCONTACTOS_PRIMARY;
    public static final UniqueKey<UsuarioscontactosRecord> KEY_USUARIOSCONTACTOS_IDUSUARIOSCONTACTOS_UNIQUE = UniqueKeys0.KEY_USUARIOSCONTACTOS_IDUSUARIOSCONTACTOS_UNIQUE;
    public static final UniqueKey<UsuariosdispositivosvirtualesRecord> KEY_USUARIOSDISPOSITIVOSVIRTUALES_PRIMARY = UniqueKeys0.KEY_USUARIOSDISPOSITIVOSVIRTUALES_PRIMARY;
    public static final UniqueKey<UsuariosdispositivosvirtualesRecord> KEY_USUARIOSDISPOSITIVOSVIRTUALES_IDUSUARIOSDISPOSITIVOSVIRTUAL_UNIQUE = UniqueKeys0.KEY_USUARIOSDISPOSITIVOSVIRTUALES_IDUSUARIOSDISPOSITIVOSVIRTUAL_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CanalesRecord, LocalizacionesRecord> FK_LOCALIZACIONCANALES = ForeignKeys0.FK_LOCALIZACIONCANALES;
    public static final ForeignKey<CanalesRecord, EmpresaRecord> FK_EMPRESACANALES = ForeignKeys0.FK_EMPRESACANALES;
    public static final ForeignKey<ContenidocanalRecord, CanalesRecord> FK_CONTENIDOCANAL_CANALES = ForeignKeys0.FK_CONTENIDOCANAL_CANALES;
    public static final ForeignKey<ContenidosinicialesRecord, LocalizacionesRecord> FK_CONTENIDOSINICIALES_LOCALIZACIONES1 = ForeignKeys0.FK_CONTENIDOSINICIALES_LOCALIZACIONES1;
    public static final ForeignKey<ContenidosmultimediaRecord, UsuariosRecord> FK_USUARIOSEMISOR = ForeignKeys0.FK_USUARIOSEMISOR;
    public static final ForeignKey<ContenidosmultimediaRecord, DispositivosvirtualesRecord> FK_CONTENIDOMULTIMEDIA = ForeignKeys0.FK_CONTENIDOMULTIMEDIA;
    public static final ForeignKey<ContenidosmultimediaRecord, ContenidosfisicosRecord> FK_CONTENIDOFISICO = ForeignKeys0.FK_CONTENIDOFISICO;
    public static final ForeignKey<DispositivosfisicosRecord, NumerosserieRecord> FK_DISPOSITIVOSFISICOS_NUMEROSERIE1 = ForeignKeys0.FK_DISPOSITIVOSFISICOS_NUMEROSERIE1;
    public static final ForeignKey<DispositivosfisicosRecord, LocalizacionesRecord> FK_LOCALIZACION = ForeignKeys0.FK_LOCALIZACION;
    public static final ForeignKey<DispositivosfisicosRecord, EmpresaRecord> FK_EMPRESAMARCO = ForeignKeys0.FK_EMPRESAMARCO;
    public static final ForeignKey<DispositivosvirtualesRecord, DispositivosfisicosRecord> FK_DISPOSITIVOFISICO = ForeignKeys0.FK_DISPOSITIVOFISICO;
    public static final ForeignKey<DispositivosvirtualesRecord, UsuariosRecord> FK_USUARIOSPROPIETARIOS = ForeignKeys0.FK_USUARIOSPROPIETARIOS;
    public static final ForeignKey<DispositivosvirtualesRecord, DispositivosvirtualesRecord> FK_PADRE = ForeignKeys0.FK_PADRE;
    public static final ForeignKey<EstadocontenidomultimediaRecord, ContenidosmultimediaRecord> FK_CONTENIDOMULTIMEDIAESTADO = ForeignKeys0.FK_CONTENIDOMULTIMEDIAESTADO;
    public static final ForeignKey<EstadocontenidomultimediaRecord, DispositivosvirtualesRecord> FK_DISPOSITIVOVIRTUALESTADO = ForeignKeys0.FK_DISPOSITIVOVIRTUALESTADO;
    public static final ForeignKey<LocalizacionesRecord, EmpresaRecord> FK_EMPRESALOC = ForeignKeys0.FK_EMPRESALOC;
    public static final ForeignKey<NotificacionesRecord, UsuariosRecord> FK_EMISOR = ForeignKeys0.FK_EMISOR;
    public static final ForeignKey<NotificacionesRecord, UsuariosRecord> FK_RECEPTOR = ForeignKeys0.FK_RECEPTOR;
    public static final ForeignKey<NumerosserieRecord, EmpresaRecord> FK_EMPRESA_NUMSERIE = ForeignKeys0.FK_EMPRESA_NUMSERIE;
    public static final ForeignKey<SmartphonesRecord, UsuariosRecord> FK_USUARIOSMARTPHONE = ForeignKeys0.FK_USUARIOSMARTPHONE;
    public static final ForeignKey<UsuariosadminRecord, EmpresaRecord> FK_EMPRESA = ForeignKeys0.FK_EMPRESA;
    public static final ForeignKey<UsuariosadminlocalizacionesRecord, UsuariosadminRecord> FK_USUARIOSADMINLOCALIZACIONES = ForeignKeys0.FK_USUARIOSADMINLOCALIZACIONES;
    public static final ForeignKey<UsuariosadminlocalizacionesRecord, LocalizacionesRecord> FK_LOCALIZACIONESUSUARIOSADMIN = ForeignKeys0.FK_LOCALIZACIONESUSUARIOSADMIN;
    public static final ForeignKey<UsuarioscontactosRecord, UsuariosRecord> FK_USUARIOS = ForeignKeys0.FK_USUARIOS;
    public static final ForeignKey<UsuarioscontactosRecord, UsuariosRecord> FK_USUARIOSCONTACTOS_USUARIOS1 = ForeignKeys0.FK_USUARIOSCONTACTOS_USUARIOS1;
    public static final ForeignKey<UsuariosdispositivosvirtualesRecord, UsuariosRecord> FK_USUARIOSDISPVIRTUALES = ForeignKeys0.FK_USUARIOSDISPVIRTUALES;
    public static final ForeignKey<UsuariosdispositivosvirtualesRecord, DispositivosvirtualesRecord> FK_DISPOSITIVOSVIRTUALES = ForeignKeys0.FK_DISPOSITIVOSVIRTUALES;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ActualizacionesRecord, Integer> IDENTITY_ACTUALIZACIONES = createIdentity(Actualizaciones.ACTUALIZACIONES, Actualizaciones.ACTUALIZACIONES.IDACTUALIZACION);
        public static Identity<CanalesRecord, Integer> IDENTITY_CANALES = createIdentity(Canales.CANALES, Canales.CANALES.IDCANAL);
        public static Identity<ContenidocanalRecord, Integer> IDENTITY_CONTENIDOCANAL = createIdentity(Contenidocanal.CONTENIDOCANAL, Contenidocanal.CONTENIDOCANAL.IDCONTENIDOCANAL);
        public static Identity<ContenidosfisicosRecord, Integer> IDENTITY_CONTENIDOSFISICOS = createIdentity(Contenidosfisicos.CONTENIDOSFISICOS, Contenidosfisicos.CONTENIDOSFISICOS.IDCONTENIDOFISICO);
        public static Identity<ContenidosinicialesRecord, Integer> IDENTITY_CONTENIDOSINICIALES = createIdentity(Contenidosiniciales.CONTENIDOSINICIALES, Contenidosiniciales.CONTENIDOSINICIALES.IDCONTENIDOINICIAL);
        public static Identity<ContenidosmultimediaRecord, Integer> IDENTITY_CONTENIDOSMULTIMEDIA = createIdentity(Contenidosmultimedia.CONTENIDOSMULTIMEDIA, Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDCONTENIDOMULTIMEDIA);
        public static Identity<DispositivosfisicosRecord, Integer> IDENTITY_DISPOSITIVOSFISICOS = createIdentity(Dispositivosfisicos.DISPOSITIVOSFISICOS, Dispositivosfisicos.DISPOSITIVOSFISICOS.IDDISPOSITIVOSFISICO);
        public static Identity<DispositivosvirtualesRecord, Integer> IDENTITY_DISPOSITIVOSVIRTUALES = createIdentity(Dispositivosvirtuales.DISPOSITIVOSVIRTUALES, Dispositivosvirtuales.DISPOSITIVOSVIRTUALES.IDDISPOSITIVOVIRTUAL);
        public static Identity<EmpresaRecord, Integer> IDENTITY_EMPRESA = createIdentity(Empresa.EMPRESA, Empresa.EMPRESA.IDEMPRESA);
        public static Identity<EstadocontenidomultimediaRecord, Integer> IDENTITY_ESTADOCONTENIDOMULTIMEDIA = createIdentity(Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA, Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDESTADOCONTENIDOMULTIMEDIA);
        public static Identity<LocalizacionesRecord, Integer> IDENTITY_LOCALIZACIONES = createIdentity(Localizaciones.LOCALIZACIONES, Localizaciones.LOCALIZACIONES.IDLOCALIZACION);
        public static Identity<NotificacionesRecord, Integer> IDENTITY_NOTIFICACIONES = createIdentity(Notificaciones.NOTIFICACIONES, Notificaciones.NOTIFICACIONES.IDNOTIFICACION);
        public static Identity<NotificacionespushRecord, Integer> IDENTITY_NOTIFICACIONESPUSH = createIdentity(Notificacionespush.NOTIFICACIONESPUSH, Notificacionespush.NOTIFICACIONESPUSH.IDNOTIFICACIONPUSH);
        public static Identity<NumerosserieRecord, Integer> IDENTITY_NUMEROSSERIE = createIdentity(Numerosserie.NUMEROSSERIE, Numerosserie.NUMEROSSERIE.IDNUMEROSERIE);
        public static Identity<SmartphonesRecord, Integer> IDENTITY_SMARTPHONES = createIdentity(Smartphones.SMARTPHONES, Smartphones.SMARTPHONES.IDSMARTPHONE);
        public static Identity<UsuariosRecord, Integer> IDENTITY_USUARIOS = createIdentity(Usuarios.USUARIOS, Usuarios.USUARIOS.IDUSUARIO);
        public static Identity<UsuariosadminRecord, Integer> IDENTITY_USUARIOSADMIN = createIdentity(Usuariosadmin.USUARIOSADMIN, Usuariosadmin.USUARIOSADMIN.IDUSUARIOSADMIN);
        public static Identity<UsuariosadminlocalizacionesRecord, Integer> IDENTITY_USUARIOSADMINLOCALIZACIONES = createIdentity(Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES, Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDUSUARIOADMINLOCALIZACION);
        public static Identity<UsuarioscontactosRecord, Integer> IDENTITY_USUARIOSCONTACTOS = createIdentity(Usuarioscontactos.USUARIOSCONTACTOS, Usuarioscontactos.USUARIOSCONTACTOS.IDUSUARIOSCONTACTOS);
        public static Identity<UsuariosdispositivosvirtualesRecord, Integer> IDENTITY_USUARIOSDISPOSITIVOSVIRTUALES = createIdentity(Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES, Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDUSUARIOSDISPOSITIVOSVIRTUAL);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ActualizacionesRecord> KEY_ACTUALIZACIONES_PRIMARY = createUniqueKey(Actualizaciones.ACTUALIZACIONES, "KEY_Actualizaciones_PRIMARY", Actualizaciones.ACTUALIZACIONES.IDACTUALIZACION);
        public static final UniqueKey<ActualizacionesRecord> KEY_ACTUALIZACIONES_IDACTUALIZACION_UNIQUE = createUniqueKey(Actualizaciones.ACTUALIZACIONES, "KEY_Actualizaciones_idActualizacion_UNIQUE", Actualizaciones.ACTUALIZACIONES.IDACTUALIZACION);
        public static final UniqueKey<CanalesRecord> KEY_CANALES_PRIMARY = createUniqueKey(Canales.CANALES, "KEY_Canales_PRIMARY", Canales.CANALES.IDCANAL);
        public static final UniqueKey<CanalesRecord> KEY_CANALES_IDCANAL_UNIQUE = createUniqueKey(Canales.CANALES, "KEY_Canales_idcanal_UNIQUE", Canales.CANALES.IDCANAL);
        public static final UniqueKey<ContenidocanalRecord> KEY_CONTENIDOCANAL_PRIMARY = createUniqueKey(Contenidocanal.CONTENIDOCANAL, "KEY_ContenidoCanal_PRIMARY", Contenidocanal.CONTENIDOCANAL.IDCONTENIDOCANAL);
        public static final UniqueKey<ContenidosfisicosRecord> KEY_CONTENIDOSFISICOS_PRIMARY = createUniqueKey(Contenidosfisicos.CONTENIDOSFISICOS, "KEY_ContenidosFisicos_PRIMARY", Contenidosfisicos.CONTENIDOSFISICOS.IDCONTENIDOFISICO);
        public static final UniqueKey<ContenidosfisicosRecord> KEY_CONTENIDOSFISICOS_IDCONTENIDOFISICO_UNIQUE = createUniqueKey(Contenidosfisicos.CONTENIDOSFISICOS, "KEY_ContenidosFisicos_idContenidoFisico_UNIQUE", Contenidosfisicos.CONTENIDOSFISICOS.IDCONTENIDOFISICO);
        public static final UniqueKey<ContenidosinicialesRecord> KEY_CONTENIDOSINICIALES_PRIMARY = createUniqueKey(Contenidosiniciales.CONTENIDOSINICIALES, "KEY_ContenidosIniciales_PRIMARY", Contenidosiniciales.CONTENIDOSINICIALES.IDCONTENIDOINICIAL, Contenidosiniciales.CONTENIDOSINICIALES.IDLOCALIZACION);
        public static final UniqueKey<ContenidosinicialesRecord> KEY_CONTENIDOSINICIALES_IDCONTENIDOINICIAL_UNIQUE = createUniqueKey(Contenidosiniciales.CONTENIDOSINICIALES, "KEY_ContenidosIniciales_idContenidoInicial_UNIQUE", Contenidosiniciales.CONTENIDOSINICIALES.IDCONTENIDOINICIAL);
        public static final UniqueKey<ContenidosmultimediaRecord> KEY_CONTENIDOSMULTIMEDIA_PRIMARY = createUniqueKey(Contenidosmultimedia.CONTENIDOSMULTIMEDIA, "KEY_ContenidosMultimedia_PRIMARY", Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDCONTENIDOMULTIMEDIA);
        public static final UniqueKey<ContenidosmultimediaRecord> KEY_CONTENIDOSMULTIMEDIA_IDCONTENIDOMULTIMEDIA_UNIQUE = createUniqueKey(Contenidosmultimedia.CONTENIDOSMULTIMEDIA, "KEY_ContenidosMultimedia_idContenidoMultimedia_UNIQUE", Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDCONTENIDOMULTIMEDIA);
        public static final UniqueKey<DispositivosfisicosRecord> KEY_DISPOSITIVOSFISICOS_PRIMARY = createUniqueKey(Dispositivosfisicos.DISPOSITIVOSFISICOS, "KEY_DispositivosFisicos_PRIMARY", Dispositivosfisicos.DISPOSITIVOSFISICOS.IDDISPOSITIVOSFISICO);
        public static final UniqueKey<DispositivosfisicosRecord> KEY_DISPOSITIVOSFISICOS_IDDISPOSITIVOSFISICOS_UNIQUE = createUniqueKey(Dispositivosfisicos.DISPOSITIVOSFISICOS, "KEY_DispositivosFisicos_idDispositivosFisicos_UNIQUE", Dispositivosfisicos.DISPOSITIVOSFISICOS.IDDISPOSITIVOSFISICO);
        public static final UniqueKey<DispositivosvirtualesRecord> KEY_DISPOSITIVOSVIRTUALES_PRIMARY = createUniqueKey(Dispositivosvirtuales.DISPOSITIVOSVIRTUALES, "KEY_DispositivosVirtuales_PRIMARY", Dispositivosvirtuales.DISPOSITIVOSVIRTUALES.IDDISPOSITIVOVIRTUAL);
        public static final UniqueKey<DispositivosvirtualesRecord> KEY_DISPOSITIVOSVIRTUALES_IDDISPOSITIVOSVIRTUAL_UNIQUE = createUniqueKey(Dispositivosvirtuales.DISPOSITIVOSVIRTUALES, "KEY_DispositivosVirtuales_idDispositivosVirtual_UNIQUE", Dispositivosvirtuales.DISPOSITIVOSVIRTUALES.IDDISPOSITIVOVIRTUAL);
        public static final UniqueKey<DispositivosvirtualesRecord> KEY_DISPOSITIVOSVIRTUALES_UUID_UNIQUE = createUniqueKey(Dispositivosvirtuales.DISPOSITIVOSVIRTUALES, "KEY_DispositivosVirtuales_uuid_UNIQUE", Dispositivosvirtuales.DISPOSITIVOSVIRTUALES.UUID);
        public static final UniqueKey<EmpresaRecord> KEY_EMPRESA_PRIMARY = createUniqueKey(Empresa.EMPRESA, "KEY_Empresa_PRIMARY", Empresa.EMPRESA.IDEMPRESA);
        public static final UniqueKey<EmpresaRecord> KEY_EMPRESA_IDEMPRESA_UNIQUE = createUniqueKey(Empresa.EMPRESA, "KEY_Empresa_idEmpresa_UNIQUE", Empresa.EMPRESA.IDEMPRESA);
        public static final UniqueKey<EstadocontenidomultimediaRecord> KEY_ESTADOCONTENIDOMULTIMEDIA_PRIMARY = createUniqueKey(Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA, "KEY_EstadoContenidoMultimedia_PRIMARY", Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDESTADOCONTENIDOMULTIMEDIA, Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDCONTENIDOMULTIMEDIA, Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDDISPOSITIVOVIRTUAL);
        public static final UniqueKey<EstadocontenidomultimediaRecord> KEY_ESTADOCONTENIDOMULTIMEDIA_IDESTADOCONTENIDOMULTIMEDIA_UNIQUE = createUniqueKey(Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA, "KEY_EstadoContenidoMultimedia_idEstadoContenidoMultimedia_UNIQUE", Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDESTADOCONTENIDOMULTIMEDIA);
        public static final UniqueKey<LocalizacionesRecord> KEY_LOCALIZACIONES_PRIMARY = createUniqueKey(Localizaciones.LOCALIZACIONES, "KEY_Localizaciones_PRIMARY", Localizaciones.LOCALIZACIONES.IDLOCALIZACION, Localizaciones.LOCALIZACIONES.IDEMPRESA);
        public static final UniqueKey<LocalizacionesRecord> KEY_LOCALIZACIONES_IDLOCALIZACION_UNIQUE = createUniqueKey(Localizaciones.LOCALIZACIONES, "KEY_Localizaciones_idLocalizacion_UNIQUE", Localizaciones.LOCALIZACIONES.IDLOCALIZACION);
        public static final UniqueKey<NotificacionesRecord> KEY_NOTIFICACIONES_PRIMARY = createUniqueKey(Notificaciones.NOTIFICACIONES, "KEY_Notificaciones_PRIMARY", Notificaciones.NOTIFICACIONES.IDNOTIFICACION);
        public static final UniqueKey<NotificacionesRecord> KEY_NOTIFICACIONES_IDNOTIFICACION_UNIQUE = createUniqueKey(Notificaciones.NOTIFICACIONES, "KEY_Notificaciones_idNotificacion_UNIQUE", Notificaciones.NOTIFICACIONES.IDNOTIFICACION);
        public static final UniqueKey<NotificacionespushRecord> KEY_NOTIFICACIONESPUSH_PRIMARY = createUniqueKey(Notificacionespush.NOTIFICACIONESPUSH, "KEY_NotificacionesPush_PRIMARY", Notificacionespush.NOTIFICACIONESPUSH.IDNOTIFICACIONPUSH);
        public static final UniqueKey<NotificacionespushRecord> KEY_NOTIFICACIONESPUSH_IDNOTIFICACIONPUSH_UNIQUE = createUniqueKey(Notificacionespush.NOTIFICACIONESPUSH, "KEY_NotificacionesPush_idNotificacionPush_UNIQUE", Notificacionespush.NOTIFICACIONESPUSH.IDNOTIFICACIONPUSH);
        public static final UniqueKey<NotificacionespushRecord> KEY_NOTIFICACIONESPUSH_IDMENSAJE_UNIQUE = createUniqueKey(Notificacionespush.NOTIFICACIONESPUSH, "KEY_NotificacionesPush_idMensaje_UNIQUE", Notificacionespush.NOTIFICACIONESPUSH.IDMENSAJE);
        public static final UniqueKey<NumerosserieRecord> KEY_NUMEROSSERIE_PRIMARY = createUniqueKey(Numerosserie.NUMEROSSERIE, "KEY_NumerosSerie_PRIMARY", Numerosserie.NUMEROSSERIE.IDNUMEROSERIE, Numerosserie.NUMEROSSERIE.IDEMPRESA);
        public static final UniqueKey<NumerosserieRecord> KEY_NUMEROSSERIE_IDNUMEROSERIE_UNIQUE = createUniqueKey(Numerosserie.NUMEROSSERIE, "KEY_NumerosSerie_idNumeroSerie_UNIQUE", Numerosserie.NUMEROSSERIE.IDNUMEROSERIE);
        public static final UniqueKey<SmartphonesRecord> KEY_SMARTPHONES_PRIMARY = createUniqueKey(Smartphones.SMARTPHONES, "KEY_SmartPhones_PRIMARY", Smartphones.SMARTPHONES.IDSMARTPHONE, Smartphones.SMARTPHONES.IDUSUARIO);
        public static final UniqueKey<SmartphonesRecord> KEY_SMARTPHONES_IDSMARTPHONE_UNIQUE = createUniqueKey(Smartphones.SMARTPHONES, "KEY_SmartPhones_idSmartPhone_UNIQUE", Smartphones.SMARTPHONES.IDSMARTPHONE);
        public static final UniqueKey<UsuariosRecord> KEY_USUARIOS_PRIMARY = createUniqueKey(Usuarios.USUARIOS, "KEY_Usuarios_PRIMARY", Usuarios.USUARIOS.IDUSUARIO);
        public static final UniqueKey<UsuariosRecord> KEY_USUARIOS_IDUSUARIO_UNIQUE = createUniqueKey(Usuarios.USUARIOS, "KEY_Usuarios_idUsuario_UNIQUE", Usuarios.USUARIOS.IDUSUARIO);
        public static final UniqueKey<UsuariosRecord> KEY_USUARIOS_EMAIL_UNIQUE = createUniqueKey(Usuarios.USUARIOS, "KEY_Usuarios_email_UNIQUE", Usuarios.USUARIOS.EMAIL);
        public static final UniqueKey<UsuariosRecord> KEY_USUARIOS_TELEFONO_UNIQUE = createUniqueKey(Usuarios.USUARIOS, "KEY_Usuarios_telefono_UNIQUE", Usuarios.USUARIOS.TELEFONO);
        public static final UniqueKey<UsuariosadminRecord> KEY_USUARIOSADMIN_PRIMARY = createUniqueKey(Usuariosadmin.USUARIOSADMIN, "KEY_UsuariosAdmin_PRIMARY", Usuariosadmin.USUARIOSADMIN.IDUSUARIOSADMIN);
        public static final UniqueKey<UsuariosadminRecord> KEY_USUARIOSADMIN_IDUSUARIOSADMIN_UNIQUE = createUniqueKey(Usuariosadmin.USUARIOSADMIN, "KEY_UsuariosAdmin_idUsuariosAdmin_UNIQUE", Usuariosadmin.USUARIOSADMIN.IDUSUARIOSADMIN);
        public static final UniqueKey<UsuariosadminlocalizacionesRecord> KEY_USUARIOSADMINLOCALIZACIONES_PRIMARY = createUniqueKey(Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES, "KEY_UsuariosAdminLocalizaciones_PRIMARY", Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDUSUARIOADMINLOCALIZACION, Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDLOCALIZACION, Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDUSUARIOADMIN);
        public static final UniqueKey<UsuariosadminlocalizacionesRecord> KEY_USUARIOSADMINLOCALIZACIONES_IDUSUARIOADMINLOCALIZACION_UNIQUE = createUniqueKey(Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES, "KEY_UsuariosAdminLocalizaciones_idUsuarioAdminLocalizacion_UNIQUE", Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDUSUARIOADMINLOCALIZACION);
        public static final UniqueKey<UsuarioscontactosRecord> KEY_USUARIOSCONTACTOS_PRIMARY = createUniqueKey(Usuarioscontactos.USUARIOSCONTACTOS, "KEY_UsuariosContactos_PRIMARY", Usuarioscontactos.USUARIOSCONTACTOS.IDUSUARIOSCONTACTOS);
        public static final UniqueKey<UsuarioscontactosRecord> KEY_USUARIOSCONTACTOS_IDUSUARIOSCONTACTOS_UNIQUE = createUniqueKey(Usuarioscontactos.USUARIOSCONTACTOS, "KEY_UsuariosContactos_idUsuariosContactos_UNIQUE", Usuarioscontactos.USUARIOSCONTACTOS.IDUSUARIOSCONTACTOS);
        public static final UniqueKey<UsuariosdispositivosvirtualesRecord> KEY_USUARIOSDISPOSITIVOSVIRTUALES_PRIMARY = createUniqueKey(Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES, "KEY_UsuariosDispositivosVirtuales_PRIMARY", Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDUSUARIOSDISPOSITIVOSVIRTUAL, Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDUSUARIO, Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDDISPOSITIVOVIRTUAL);
        public static final UniqueKey<UsuariosdispositivosvirtualesRecord> KEY_USUARIOSDISPOSITIVOSVIRTUALES_IDUSUARIOSDISPOSITIVOSVIRTUAL_UNIQUE = createUniqueKey(Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES, "KEY_UsuariosDispositivosVirtuales_idUsuariosDispositivosVirtual_UNIQUE", Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDUSUARIOSDISPOSITIVOSVIRTUAL);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CanalesRecord, LocalizacionesRecord> FK_LOCALIZACIONCANALES = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_LOCALIZACIONES_PRIMARY, Canales.CANALES, "FK_LocalizacionCanales", Canales.CANALES.IDLOCALIZACION);
        public static final ForeignKey<CanalesRecord, EmpresaRecord> FK_EMPRESACANALES = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_EMPRESA_PRIMARY, Canales.CANALES, "FK_EmpresaCanales", Canales.CANALES.IDEMPRESA);
        public static final ForeignKey<ContenidocanalRecord, CanalesRecord> FK_CONTENIDOCANAL_CANALES = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_CANALES_PRIMARY, Contenidocanal.CONTENIDOCANAL, "fk_contenidoCanal_canales", Contenidocanal.CONTENIDOCANAL.IDCANAL);
        public static final ForeignKey<ContenidosinicialesRecord, LocalizacionesRecord> FK_CONTENIDOSINICIALES_LOCALIZACIONES1 = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_LOCALIZACIONES_PRIMARY, Contenidosiniciales.CONTENIDOSINICIALES, "fk_ContenidosIniciales_Localizaciones1", Contenidosiniciales.CONTENIDOSINICIALES.IDLOCALIZACION);
        public static final ForeignKey<ContenidosmultimediaRecord, UsuariosRecord> FK_USUARIOSEMISOR = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOS_PRIMARY, Contenidosmultimedia.CONTENIDOSMULTIMEDIA, "fk_usuariosEmisor", Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDUSUARIOEMISOR);
        public static final ForeignKey<ContenidosmultimediaRecord, DispositivosvirtualesRecord> FK_CONTENIDOMULTIMEDIA = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_DISPOSITIVOSVIRTUALES_PRIMARY, Contenidosmultimedia.CONTENIDOSMULTIMEDIA, "fk_ContenidoMultimedia", Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDDISPOSITIVOVIRTUAL);
        public static final ForeignKey<ContenidosmultimediaRecord, ContenidosfisicosRecord> FK_CONTENIDOFISICO = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_CONTENIDOSFISICOS_PRIMARY, Contenidosmultimedia.CONTENIDOSMULTIMEDIA, "FK_ContenidoFisico", Contenidosmultimedia.CONTENIDOSMULTIMEDIA.IDCONTENIDOFISICO);
        public static final ForeignKey<DispositivosfisicosRecord, NumerosserieRecord> FK_DISPOSITIVOSFISICOS_NUMEROSERIE1 = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_NUMEROSSERIE_PRIMARY, Dispositivosfisicos.DISPOSITIVOSFISICOS, "fk_DispositivosFisicos_NumeroSerie1", Dispositivosfisicos.DISPOSITIVOSFISICOS.IDNUMEROSERIE);
        public static final ForeignKey<DispositivosfisicosRecord, LocalizacionesRecord> FK_LOCALIZACION = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_LOCALIZACIONES_PRIMARY, Dispositivosfisicos.DISPOSITIVOSFISICOS, "fk_localizacion", Dispositivosfisicos.DISPOSITIVOSFISICOS.IDLOCALIZACION);
        public static final ForeignKey<DispositivosfisicosRecord, EmpresaRecord> FK_EMPRESAMARCO = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_EMPRESA_PRIMARY, Dispositivosfisicos.DISPOSITIVOSFISICOS, "FK_EmpresaMarco", Dispositivosfisicos.DISPOSITIVOSFISICOS.IDEMPRESA);
        public static final ForeignKey<DispositivosvirtualesRecord, DispositivosfisicosRecord> FK_DISPOSITIVOFISICO = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_DISPOSITIVOSFISICOS_PRIMARY, Dispositivosvirtuales.DISPOSITIVOSVIRTUALES, "FK_DispositivoFisico", Dispositivosvirtuales.DISPOSITIVOSVIRTUALES.IDDISPOSITIVOFISICO);
        public static final ForeignKey<DispositivosvirtualesRecord, UsuariosRecord> FK_USUARIOSPROPIETARIOS = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOS_PRIMARY, Dispositivosvirtuales.DISPOSITIVOSVIRTUALES, "FK_UsuariosPropietarios", Dispositivosvirtuales.DISPOSITIVOSVIRTUALES.IDPROPIETARIO);
        public static final ForeignKey<DispositivosvirtualesRecord, DispositivosvirtualesRecord> FK_PADRE = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_DISPOSITIVOSVIRTUALES_PRIMARY, Dispositivosvirtuales.DISPOSITIVOSVIRTUALES, "FK_Padre", Dispositivosvirtuales.DISPOSITIVOSVIRTUALES.IDPADRE);
        public static final ForeignKey<EstadocontenidomultimediaRecord, ContenidosmultimediaRecord> FK_CONTENIDOMULTIMEDIAESTADO = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_CONTENIDOSMULTIMEDIA_PRIMARY, Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA, "FK_ContenidoMultimediaEstado", Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDCONTENIDOMULTIMEDIA);
        public static final ForeignKey<EstadocontenidomultimediaRecord, DispositivosvirtualesRecord> FK_DISPOSITIVOVIRTUALESTADO = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_DISPOSITIVOSVIRTUALES_PRIMARY, Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA, "FK_DispositivoVirtualEstado", Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA.IDDISPOSITIVOVIRTUAL);
        public static final ForeignKey<LocalizacionesRecord, EmpresaRecord> FK_EMPRESALOC = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_EMPRESA_PRIMARY, Localizaciones.LOCALIZACIONES, "fk_empresaLoc", Localizaciones.LOCALIZACIONES.IDEMPRESA);
        public static final ForeignKey<NotificacionesRecord, UsuariosRecord> FK_EMISOR = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOS_PRIMARY, Notificaciones.NOTIFICACIONES, "fk_emisor", Notificaciones.NOTIFICACIONES.IDUSUARIOEMISOR);
        public static final ForeignKey<NotificacionesRecord, UsuariosRecord> FK_RECEPTOR = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOS_PRIMARY, Notificaciones.NOTIFICACIONES, "fk_receptor", Notificaciones.NOTIFICACIONES.IDUSUARIORECEPTOR);
        public static final ForeignKey<NumerosserieRecord, EmpresaRecord> FK_EMPRESA_NUMSERIE = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_EMPRESA_PRIMARY, Numerosserie.NUMEROSSERIE, "FK_EMPRESA_NUMSERIE", Numerosserie.NUMEROSSERIE.IDEMPRESA);
        public static final ForeignKey<SmartphonesRecord, UsuariosRecord> FK_USUARIOSMARTPHONE = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOS_PRIMARY, Smartphones.SMARTPHONES, "FK_UsuarioSmartPhone", Smartphones.SMARTPHONES.IDUSUARIO);
        public static final ForeignKey<UsuariosadminRecord, EmpresaRecord> FK_EMPRESA = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_EMPRESA_PRIMARY, Usuariosadmin.USUARIOSADMIN, "fk_empresa", Usuariosadmin.USUARIOSADMIN.IDEMPRESA);
        public static final ForeignKey<UsuariosadminlocalizacionesRecord, UsuariosadminRecord> FK_USUARIOSADMINLOCALIZACIONES = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOSADMIN_PRIMARY, Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES, "FK_USUARIOSADMINLOCALIZACIONES", Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDUSUARIOADMIN);
        public static final ForeignKey<UsuariosadminlocalizacionesRecord, LocalizacionesRecord> FK_LOCALIZACIONESUSUARIOSADMIN = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_LOCALIZACIONES_PRIMARY, Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES, "FK_LocalizacionesUsuariosAdmin", Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES.IDLOCALIZACION);
        public static final ForeignKey<UsuarioscontactosRecord, UsuariosRecord> FK_USUARIOS = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOS_PRIMARY, Usuarioscontactos.USUARIOSCONTACTOS, "fk_usuarios", Usuarioscontactos.USUARIOSCONTACTOS.IDUSUARIO);
        public static final ForeignKey<UsuarioscontactosRecord, UsuariosRecord> FK_USUARIOSCONTACTOS_USUARIOS1 = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOS_PRIMARY, Usuarioscontactos.USUARIOSCONTACTOS, "fk_UsuariosContactos_Usuarios1", Usuarioscontactos.USUARIOSCONTACTOS.IDUSUARIOCONTACTO);
        public static final ForeignKey<UsuariosdispositivosvirtualesRecord, UsuariosRecord> FK_USUARIOSDISPVIRTUALES = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_USUARIOS_PRIMARY, Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES, "fk_usuariosDispVirtuales", Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDUSUARIO);
        public static final ForeignKey<UsuariosdispositivosvirtualesRecord, DispositivosvirtualesRecord> FK_DISPOSITIVOSVIRTUALES = createForeignKey(com.cimne.tic.oko.server.ws.model.Keys.KEY_DISPOSITIVOSVIRTUALES_PRIMARY, Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES, "fk_dispositivosvirtuales", Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES.IDDISPOSITIVOVIRTUAL);
    }
}
