/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model;


import com.cimne.tic.oko.server.ws.model.tables.Actualizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Canales;
import com.cimne.tic.oko.server.ws.model.tables.Contenidocanal;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosfisicos;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosiniciales;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosmultimedia;
import com.cimne.tic.oko.server.ws.model.tables.Dispositivosfisicos;
import com.cimne.tic.oko.server.ws.model.tables.Dispositivosvirtuales;
import com.cimne.tic.oko.server.ws.model.tables.Empresa;
import com.cimne.tic.oko.server.ws.model.tables.Estadocontenidomultimedia;
import com.cimne.tic.oko.server.ws.model.tables.Localizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Notificaciones;
import com.cimne.tic.oko.server.ws.model.tables.Notificacionespush;
import com.cimne.tic.oko.server.ws.model.tables.Numerosserie;
import com.cimne.tic.oko.server.ws.model.tables.Smartphones;
import com.cimne.tic.oko.server.ws.model.tables.Usuarios;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosadmin;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosadminlocalizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Usuarioscontactos;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosdispositivosvirtuales;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Oko extends SchemaImpl {

    private static final long serialVersionUID = -503974894;

    /**
     * The reference instance of <code>oko</code>
     */
    public static final Oko OKO = new Oko();

    /**
     * The table <code>oko.Actualizaciones</code>.
     */
    public final Actualizaciones ACTUALIZACIONES = com.cimne.tic.oko.server.ws.model.tables.Actualizaciones.ACTUALIZACIONES;

    /**
     * The table <code>oko.Canales</code>.
     */
    public final Canales CANALES = com.cimne.tic.oko.server.ws.model.tables.Canales.CANALES;

    /**
     * The table <code>oko.ContenidoCanal</code>.
     */
    public final Contenidocanal CONTENIDOCANAL = com.cimne.tic.oko.server.ws.model.tables.Contenidocanal.CONTENIDOCANAL;

    /**
     * The table <code>oko.ContenidosFisicos</code>.
     */
    public final Contenidosfisicos CONTENIDOSFISICOS = com.cimne.tic.oko.server.ws.model.tables.Contenidosfisicos.CONTENIDOSFISICOS;

    /**
     * The table <code>oko.ContenidosIniciales</code>.
     */
    public final Contenidosiniciales CONTENIDOSINICIALES = com.cimne.tic.oko.server.ws.model.tables.Contenidosiniciales.CONTENIDOSINICIALES;

    /**
     * The table <code>oko.ContenidosMultimedia</code>.
     */
    public final Contenidosmultimedia CONTENIDOSMULTIMEDIA = com.cimne.tic.oko.server.ws.model.tables.Contenidosmultimedia.CONTENIDOSMULTIMEDIA;

    /**
     * The table <code>oko.DispositivosFisicos</code>.
     */
    public final Dispositivosfisicos DISPOSITIVOSFISICOS = com.cimne.tic.oko.server.ws.model.tables.Dispositivosfisicos.DISPOSITIVOSFISICOS;

    /**
     * The table <code>oko.DispositivosVirtuales</code>.
     */
    public final Dispositivosvirtuales DISPOSITIVOSVIRTUALES = com.cimne.tic.oko.server.ws.model.tables.Dispositivosvirtuales.DISPOSITIVOSVIRTUALES;

    /**
     * The table <code>oko.Empresa</code>.
     */
    public final Empresa EMPRESA = com.cimne.tic.oko.server.ws.model.tables.Empresa.EMPRESA;

    /**
     * The table <code>oko.EstadoContenidoMultimedia</code>.
     */
    public final Estadocontenidomultimedia ESTADOCONTENIDOMULTIMEDIA = com.cimne.tic.oko.server.ws.model.tables.Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA;

    /**
     * The table <code>oko.Localizaciones</code>.
     */
    public final Localizaciones LOCALIZACIONES = com.cimne.tic.oko.server.ws.model.tables.Localizaciones.LOCALIZACIONES;

    /**
     * The table <code>oko.Notificaciones</code>.
     */
    public final Notificaciones NOTIFICACIONES = com.cimne.tic.oko.server.ws.model.tables.Notificaciones.NOTIFICACIONES;

    /**
     * The table <code>oko.NotificacionesPush</code>.
     */
    public final Notificacionespush NOTIFICACIONESPUSH = com.cimne.tic.oko.server.ws.model.tables.Notificacionespush.NOTIFICACIONESPUSH;

    /**
     * The table <code>oko.NumerosSerie</code>.
     */
    public final Numerosserie NUMEROSSERIE = com.cimne.tic.oko.server.ws.model.tables.Numerosserie.NUMEROSSERIE;

    /**
     * The table <code>oko.SmartPhones</code>.
     */
    public final Smartphones SMARTPHONES = com.cimne.tic.oko.server.ws.model.tables.Smartphones.SMARTPHONES;

    /**
     * The table <code>oko.Usuarios</code>.
     */
    public final Usuarios USUARIOS = com.cimne.tic.oko.server.ws.model.tables.Usuarios.USUARIOS;

    /**
     * The table <code>oko.UsuariosAdmin</code>.
     */
    public final Usuariosadmin USUARIOSADMIN = com.cimne.tic.oko.server.ws.model.tables.Usuariosadmin.USUARIOSADMIN;

    /**
     * The table <code>oko.UsuariosAdminLocalizaciones</code>.
     */
    public final Usuariosadminlocalizaciones USUARIOSADMINLOCALIZACIONES = com.cimne.tic.oko.server.ws.model.tables.Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES;

    /**
     * The table <code>oko.UsuariosContactos</code>.
     */
    public final Usuarioscontactos USUARIOSCONTACTOS = com.cimne.tic.oko.server.ws.model.tables.Usuarioscontactos.USUARIOSCONTACTOS;

    /**
     * The table <code>oko.UsuariosDispositivosVirtuales</code>.
     */
    public final Usuariosdispositivosvirtuales USUARIOSDISPOSITIVOSVIRTUALES = com.cimne.tic.oko.server.ws.model.tables.Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES;

    /**
     * No further instances allowed
     */
    private Oko() {
        super("oko", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Actualizaciones.ACTUALIZACIONES,
            Canales.CANALES,
            Contenidocanal.CONTENIDOCANAL,
            Contenidosfisicos.CONTENIDOSFISICOS,
            Contenidosiniciales.CONTENIDOSINICIALES,
            Contenidosmultimedia.CONTENIDOSMULTIMEDIA,
            Dispositivosfisicos.DISPOSITIVOSFISICOS,
            Dispositivosvirtuales.DISPOSITIVOSVIRTUALES,
            Empresa.EMPRESA,
            Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA,
            Localizaciones.LOCALIZACIONES,
            Notificaciones.NOTIFICACIONES,
            Notificacionespush.NOTIFICACIONESPUSH,
            Numerosserie.NUMEROSSERIE,
            Smartphones.SMARTPHONES,
            Usuarios.USUARIOS,
            Usuariosadmin.USUARIOSADMIN,
            Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES,
            Usuarioscontactos.USUARIOSCONTACTOS,
            Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES);
    }
}
