/*
 * This file is generated by jOOQ.
*/
package com.cimne.tic.oko.server.ws.model;


import com.cimne.tic.oko.server.ws.model.tables.Actualizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Canales;
import com.cimne.tic.oko.server.ws.model.tables.Contenidocanal;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosfisicos;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosiniciales;
import com.cimne.tic.oko.server.ws.model.tables.Contenidosmultimedia;
import com.cimne.tic.oko.server.ws.model.tables.Dispositivosfisicos;
import com.cimne.tic.oko.server.ws.model.tables.Dispositivosvirtuales;
import com.cimne.tic.oko.server.ws.model.tables.Empresa;
import com.cimne.tic.oko.server.ws.model.tables.Estadocontenidomultimedia;
import com.cimne.tic.oko.server.ws.model.tables.Localizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Notificaciones;
import com.cimne.tic.oko.server.ws.model.tables.Notificacionespush;
import com.cimne.tic.oko.server.ws.model.tables.Numerosserie;
import com.cimne.tic.oko.server.ws.model.tables.Smartphones;
import com.cimne.tic.oko.server.ws.model.tables.Usuarios;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosadmin;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosadminlocalizaciones;
import com.cimne.tic.oko.server.ws.model.tables.Usuarioscontactos;
import com.cimne.tic.oko.server.ws.model.tables.Usuariosdispositivosvirtuales;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in oko
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>oko.Actualizaciones</code>.
     */
    public static final Actualizaciones ACTUALIZACIONES = com.cimne.tic.oko.server.ws.model.tables.Actualizaciones.ACTUALIZACIONES;

    /**
     * The table <code>oko.Canales</code>.
     */
    public static final Canales CANALES = com.cimne.tic.oko.server.ws.model.tables.Canales.CANALES;

    /**
     * The table <code>oko.ContenidoCanal</code>.
     */
    public static final Contenidocanal CONTENIDOCANAL = com.cimne.tic.oko.server.ws.model.tables.Contenidocanal.CONTENIDOCANAL;

    /**
     * The table <code>oko.ContenidosFisicos</code>.
     */
    public static final Contenidosfisicos CONTENIDOSFISICOS = com.cimne.tic.oko.server.ws.model.tables.Contenidosfisicos.CONTENIDOSFISICOS;

    /**
     * The table <code>oko.ContenidosIniciales</code>.
     */
    public static final Contenidosiniciales CONTENIDOSINICIALES = com.cimne.tic.oko.server.ws.model.tables.Contenidosiniciales.CONTENIDOSINICIALES;

    /**
     * The table <code>oko.ContenidosMultimedia</code>.
     */
    public static final Contenidosmultimedia CONTENIDOSMULTIMEDIA = com.cimne.tic.oko.server.ws.model.tables.Contenidosmultimedia.CONTENIDOSMULTIMEDIA;

    /**
     * The table <code>oko.DispositivosFisicos</code>.
     */
    public static final Dispositivosfisicos DISPOSITIVOSFISICOS = com.cimne.tic.oko.server.ws.model.tables.Dispositivosfisicos.DISPOSITIVOSFISICOS;

    /**
     * The table <code>oko.DispositivosVirtuales</code>.
     */
    public static final Dispositivosvirtuales DISPOSITIVOSVIRTUALES = com.cimne.tic.oko.server.ws.model.tables.Dispositivosvirtuales.DISPOSITIVOSVIRTUALES;

    /**
     * The table <code>oko.Empresa</code>.
     */
    public static final Empresa EMPRESA = com.cimne.tic.oko.server.ws.model.tables.Empresa.EMPRESA;

    /**
     * The table <code>oko.EstadoContenidoMultimedia</code>.
     */
    public static final Estadocontenidomultimedia ESTADOCONTENIDOMULTIMEDIA = com.cimne.tic.oko.server.ws.model.tables.Estadocontenidomultimedia.ESTADOCONTENIDOMULTIMEDIA;

    /**
     * The table <code>oko.Localizaciones</code>.
     */
    public static final Localizaciones LOCALIZACIONES = com.cimne.tic.oko.server.ws.model.tables.Localizaciones.LOCALIZACIONES;

    /**
     * The table <code>oko.Notificaciones</code>.
     */
    public static final Notificaciones NOTIFICACIONES = com.cimne.tic.oko.server.ws.model.tables.Notificaciones.NOTIFICACIONES;

    /**
     * The table <code>oko.NotificacionesPush</code>.
     */
    public static final Notificacionespush NOTIFICACIONESPUSH = com.cimne.tic.oko.server.ws.model.tables.Notificacionespush.NOTIFICACIONESPUSH;

    /**
     * The table <code>oko.NumerosSerie</code>.
     */
    public static final Numerosserie NUMEROSSERIE = com.cimne.tic.oko.server.ws.model.tables.Numerosserie.NUMEROSSERIE;

    /**
     * The table <code>oko.SmartPhones</code>.
     */
    public static final Smartphones SMARTPHONES = com.cimne.tic.oko.server.ws.model.tables.Smartphones.SMARTPHONES;

    /**
     * The table <code>oko.Usuarios</code>.
     */
    public static final Usuarios USUARIOS = com.cimne.tic.oko.server.ws.model.tables.Usuarios.USUARIOS;

    /**
     * The table <code>oko.UsuariosAdmin</code>.
     */
    public static final Usuariosadmin USUARIOSADMIN = com.cimne.tic.oko.server.ws.model.tables.Usuariosadmin.USUARIOSADMIN;

    /**
     * The table <code>oko.UsuariosAdminLocalizaciones</code>.
     */
    public static final Usuariosadminlocalizaciones USUARIOSADMINLOCALIZACIONES = com.cimne.tic.oko.server.ws.model.tables.Usuariosadminlocalizaciones.USUARIOSADMINLOCALIZACIONES;

    /**
     * The table <code>oko.UsuariosContactos</code>.
     */
    public static final Usuarioscontactos USUARIOSCONTACTOS = com.cimne.tic.oko.server.ws.model.tables.Usuarioscontactos.USUARIOSCONTACTOS;

    /**
     * The table <code>oko.UsuariosDispositivosVirtuales</code>.
     */
    public static final Usuariosdispositivosvirtuales USUARIOSDISPOSITIVOSVIRTUALES = com.cimne.tic.oko.server.ws.model.tables.Usuariosdispositivosvirtuales.USUARIOSDISPOSITIVOSVIRTUALES;
}
